### ISSUE TITLE
Upgrade provision app to latest spring boot version (2.1.4)

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-provisioning-app#119]
Current spring boot version of the provision app is 2.0.9.RELEASE.
Latest version of spring boot as of now is 2.1.4.RELEASE.

**Comment by clemensutschig** [comment]
@oalyman- whats the status? Is this a 1.1 candidate?

**Comment by oalyman** [comment]
It's done. And waiting for review in BIX Bitbucket.
