### ISSUE TITLE
Redirect to /home.html, and then stuck at error page

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#134]
Somehow I was redirect to `/home.html`, and then was "stuck" at the error page - only navigating directly to the provision page worked. @hugowschneider Do you remember the details of this problem

FYI @clemensutschig

**Comment by clemensutschig** [comment]
@michaelsauter can you try this with latest Master..  I reworked the entire auth cache mess lately and also amended the Security config.

**Comment by clemensutschig** [comment]
See #120

**Comment by michaelsauter** [comment]
Updated everything and tried to reproduce it (I did what happend on Tuesday: open prov app, login, then wait 3 hours, and reload). It did not break, so presumably it's fixed - or I did something slightly different, hard. to tell. Closing for now.
