### ISSUE TITLE
Provision app Should allow to add roles to an existing project 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#139]

**Comment by stitakis** [comment]
@clemensutschig I assume the admin (by default the creator of an existing) should be able to assign roles to other users. Which kind of roles? Will be the roles replicated to jira, confluence and bitbucket?  Which use case this enhancement will target?

**Comment by alanbort** [comment]
As a Project Admin I need to delegate the ability to provision applications per project to individual users or groups. This would be similar to the jira permission matrix or the Jenkins authorization matrix plugin.

Considering other pending issues (decomission provisioned applications) the permissions should be selectable on a delegated entity level (again, like Jira and Jenkins authorization matrix plugin). This would  allow additional permissions to be added in the future, but could start with simply: "View", "Provision" and "Decomission"

**Comment by alanbort** [comment]
As a Project Admin I need to delegate the ability to provision applications per project to individual users or groups. This would be similar to the jira permission matrix or the Jenkins authorization matrix plugin.

Considering other pending issues (decomission provisioned applications) the permissions should be selectable on a delegated entity level (again, like Jira and Jenkins authorization matrix plugin). This would  allow additional permissions to be added in the future, but could start with simply: "View", "Provision" and "Decomission"

**Comment by stitakis** [comment]
I think this feature is already implemented. On project creation special permissions set can be applied to define an admin, team members and read-only group. I'll close this item.
