### ISSUE TITLE
Missing role bindings?

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#14]
@michaelsauter I have a question regarding the import of the provisioning app via tailor. I had to add the system:image-puller role for the cd namespace to the system:serviceaccount:prov-cd:default manually, after I had imported the app via tailor and started to use Jenkins in the prov-cd project. Before this no Jenkins slaves could be spawned because of the missing role.
Are we missing something in the ocp-config of the provisioning app or is it even possible to export and import the necessary role bindings?

**Comment by michaelsauter** [comment]
Hmm, could be that they are missing. In theory we can import any resource, so we can also include the rolebinding. I guess I did not include them as I thought all those were added automatically ...

**Comment by tjaeschke** [comment]
Talked with Clemens about it yesterday. If you provision an app with the prov app, the bindings are set automatically in the provison scripts, but not, if you import something manually. Maybe it's a cluster configuration thing.

**Comment by clemensutschig** [comment]
@michaelsauter  / @tjaeschke  - this is expected - and either needs to go into the getting started - or into tailor. make a call and implement it that way :)

**Comment by michaelsauter** [comment]
I think we should try to put it into the templates used by Tailor. I can give that a shot and if it does not work nicely, we can add it to the getting started guide ...

**Comment by clemensutschig** [comment]
Whats the Status of this? .. the Trick is actually a little more than prov App..  in cd project we need also a binding for system:authenticated to be allowed to pull Images..  this is a 1.0 fix i suggest.

**Comment by michaelsauter** [comment]
@clemensutschig The status is that I did not look into this since my comment ... do you want to continue with your idea?

**Comment by clemensutschig** [comment]
@michaelsauter - yup .. I think this is the most sutainable way - and it also allows people to test the rundeck setup @tjaeschke  - thoughts?

**Comment by tjaeschke** [comment]
@clemensutschig  I've thought about it and I agree with you. I think this would be a good way to test the rundeck setup and if successful to have the projects in Openshift.

**Comment by clemensutschig** [comment]
@tjaeschke / @michaelsauter - with the new setup (webhook proxy - and no need for pipelines in *cd) in v1.. we could in fact remove *cd from the ocp config ... and then have rundeck provision the project..

thoughts?

**Comment by michaelsauter** [comment]
@clemensutschig Right now we create a pipeline for the prov app even in v1 because users might never push to the prov app repo (after the initial creation), therefore there would be no pipeline to trigger the initial deployment ...

**Comment by tjaeschke** [comment]
@michaelsauter I think this issue can be closed, can't it?

**Comment by michaelsauter** [comment]
I'd say yes - if it comes up again, we can open again.
