### ISSUE TITLE
Project creation/modification forms keep hidden after login

### ISSUE THREAD

**Issue by jorge-romero** [opendevstack/ods-provisioning-app#144]
After accessing the provisioning app, in the provision folder currently I can only see the title, the legend of the fieldset of choosing an option and the footer

![image](https://user-images.githubusercontent.com/12911486/58554811-3a45f500-8218-11e9-8242-abed10b8ae76.png)

I have check that the forms to create/modify a project exists;
![image](https://user-images.githubusercontent.com/12911486/58554905-737e6500-8218-11e9-9685-3ff40607bd2f.png)

Even more, if I remove the "hidden" class I'm able to see the form and provision a project:
![image](https://user-images.githubusercontent.com/12911486/58555037-cb1cd080-8218-11e9-80d9-ef94f7ec2931.png)

Could it be related with permissions or a frontend problem

**Comment by tjaeschke** [comment]
This is an issue in the application properties, If you change the crowd user and admin group to

crowd.user.group=opendevstack-users
crowd.admin.group=opendevstack-administrators

it should work.
