### ISSUE TITLE
Provision app should support reuse of shared schemes for Jira & not create permission schemes every time

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#151]
I were checking the code and here
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JiraAdapter.java#L178

you can not choose if you want to create a project from a shared configuration.

use shared configuration is useful for atlassian administrations and maintability of already created projects.

I think this should be something configurable when using provisioning app.

Right now As far as I see in the code, it seems for every project is creation a  permissions scheme

**Comment by clemensutschig** [comment]
@segator  - currently that#s intended design ..  can you specify which shared objects you'd like to reuse / configure?

**Comment by segator** [comment]
All the Schemes.(check the image)

There are 2 ways to do this.

## Creating using schemas of other project.

Jira have a a way to create project using same schemes from other project.
* This is the UI screen
![image](https://user-images.githubusercontent.com/2348131/60158319-224e9a80-97f1-11e9-85b8-9ef9132359e8.png)
* Rest API
/rest/project-templates/1.0/createshared

## When Creating through provisioning app pass parameters of the diferents scheme ID.

**Comment by rattermeyer** [comment]
So, you simply would like to specify a base project?

**Comment by rattermeyer** [comment]
Can you provide a link to the documentation?

The project-templates endpoint is [deprecated](https://developer.atlassian.com/server/jira/platform/creating-a-project-template/):

> Project template apps were originally supported in Jira 6.0 with the project-template module. However, Jira 6.0.7 introduces the project-blueprint plugin module that provides additional capabilities and is meant to substitute the project-template module. We strongly encourage you to use the project-blueprint module for project template app development, as described in this tutorial.

but [haven't found](https://community.developer.atlassian.com/t/project-blueprint-plugin-module-documentation-is-missing/11070)  documentation on it either.
Should be clear where to start.

**Comment by clemensutschig** [comment]
Richard..  Please Check the Readme. ;-)

Richard Attermeyer <notifications@github.com> schrieb am Mi., 26. Juni
2019, 13:53:

**Comment by rattermeyer** [comment]
For what? Documentation was referring to the Atlassian REST API documentation, not the project documentation. And there seems some issues with Atlassian strategy. Deprecating one endpoint and not providing documentation on the newer one (or I wasn't able to find it)

**Comment by segator** [comment]
I prefer the second option I mentioned, because it have more possibilities, imagine using the rest api of provisiong app I can pass the diferents ID's of  permission scheme, screen scheme, workflow scheme.. etc.

Using the first option means I will need to have a dummy project to be used as a reference, I don't like it.

other solution is create a plugin with the preconfigured schemes but it's a mess to maintain it, and people is going to use provisioning app probably don't know how to write atlassian  blueprints plugins.

**Comment by segator** [comment]
Any update on this?

**Comment by segator** [comment]
We should prioritize this task, because this is impacting performance on jira.
Every time prov-app creates a project it creates unecesaries schemes that affects on the jira performance.

**Comment by stitakis** [comment]
I have taken a look as requested by @segator...

Problem: 
This is impacting operation of Jira Server, because on project creation a new ```permission scheme``` is created. This makes the management of permissions scheme difficult and very time consuming. Specially if changes across many project is required.

Proposed Solution:
The idea here is to reuse ```permission scheme``` (instead of creating a new one based on a template on project create event).
There is an API in Jira that makes possible to assign a ```permission scheme``` to a project. (see https://docs.atlassian.com/software/jira/docs/api/REST/8.7.1/#api/2/project/{projectKeyOrId}/priorityscheme)
ProvApp should have a property that enables to defined the default name of the permission scheme to be assigned to a new project. If this property is not configured and to remain backwards compatible a new permission scheme should be created for every new project.

@segator @clemensutschig @rattermeyer what do you think?

**Comment by segator** [comment]
Not only permission scheme, Also screen, workflows, configuration custom field scheme.. etc
Right now our instance is messy as prov-app is creating duplicated schemes for everything, doing the system a little bit slow and very hard to maintain.
This task should be done ASAP as we are waitting since June of 2019!!

**Comment by stitakis** [comment]
@segator I took a look at how to implement. I propose to:
- a project type will optionally have an associated permission scheme name in the prov app configuration (`jira.project.template.key.<TEMPLATE-KEY>.permission-scheme-name=<PERMISSION-SCHEME-NAME>`)
- if that project scheme does not exists (it can't be found... e.g wrong name, or it does not simply exists) a new one will be created an associated to it.
- this new one permission scheme will be optionally reused by configuration (`jira.permission-scheme.reuse-created=true/false`) and set to new projects. If the property is equal `false` a new permission scheme will be created for every new project.
Sounds good?

**Comment by stitakis** [comment]
@segator 
I making progress on this... new projects will be associated to a specific permission scheme. 
This will happen if for a given project type the permission scheme name is configured in the properties file.
This will allow to reuse global permission schemes in Jira.

Question, in case that the special permissions is set, do we need to add the groups defined in that set in the global permission scheme?

**Comment by segator** [comment]
awesome news :)
if  special permissions are set, users will be asigned as role binding instead of hardcoded in the permission scheme.
The main issue is depepeding of the permission scheme configured you will have diferent role names, so in the properties you will also need a mapping admin=roleNameA , member = roleNameB or something like that

**Comment by stitakis** [comment]
@segator can you please add more details about ```...so in the properties you will also need a mapping admin=roleNameA , member = roleNameB or something like that...```
I'm trying to figure out what to do if special permissions are set? E.g. for the `projectadminGroup: ADMIN_GROUP`, do we need to this group to the global permission scheme? If yes, to which permission in that scheme this group needs to be added?

**Comment by martsec** [comment]
@segator ?

**Comment by stitakis** [comment]
@segator @martsec due lack of time, I'll not be able to finish this for ODS 3.x before my holiday. Thou I have a branch that I could push if someone want to continue. I propose to descope this item from ODS 3.x, agree?

**Comment by michaelsauter** [comment]
Fine by me.

**Comment by metmajer** [comment]
@stitakis if I recall correctly, this is causing daily issues. If that’s true, let’s pick it up when you’re back and we Release with ODS 3.1 in September @martsec

**Comment by stitakis** [comment]
@martsec @metmajer my goal is to finish this one as soon as possible. As I commented above I have a WIP branch that partially solves this issue. Unfortunatelly it turned out to be more complex and requires a bit more work. I need feedback from @segator to be able to continue on this. Agree, we should schedule this one for ODS 3.1/September.
