### ISSUE TITLE
Issue with Guava 23

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#152]
The provisioning app does not work with Guava 23.0 because of a missing Stringhelper method, that ist used in the Atlassian REST client.

We will have to change the client to https://mvnrepository.com/artifact/com.atlassian.jira/jira-rest-java-client-api?repo=atlassian-public

For this, we will have to refactor the Jira adapter.

**Comment by clemensutschig** [comment]
closed by #156
