### ISSUE TITLE
jQuery fails to load

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#153]
When trying to provision a component, I noticed the following error in the console:

```
Failed to load resource: the server responded with a status of 404 ()
```

The requested resource was: `https://domain.com/webjars/jquery/3.2.1/dist/jquery.min.js`

**Comment by clemensutschig** [comment]
@michaelsauter  - can you still login?

**Comment by michaelsauter** [comment]
I was able to provision the component, so I assume that there actually IS some jQuery being loaded, but maybe from another location. I did not investigate further, just captured the error for now.

**Comment by rattermeyer** [comment]
jquery is included twice...
