### ISSUE TITLE
Missing method breaks provisioning app

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#154]
Since version 21 Guava there is no longer the method ToStringHelper() in com.google.common.base.Objects

This method is used by the com.atlassian.jira.rest.client.domain.Project in the jira-rest-java-client

If the dependencies are not overwritten by an older Guava version, which can be achieved by restructuring the imports, the provisioning app breaks, but restructring is not guaranteed to work.

![error_ods](https://user-images.githubusercontent.com/24410591/60102428-f6cea000-975d-11e9-8e52-962af3934f94.PNG)

**Comment by stitakis** [comment]
As quick workaround, have you tried to downgrade Guava to version 20?

**Comment by tjaeschke** [comment]
> As quick workaround, have you tried to downgrade Guava to version 20?

Yes, I have and I also created a Hotfix branch in the 1.1.x branch for this, requested by @clemensutschig if the error occurs in 1.1

**Comment by tjaeschke** [comment]
Cherry picked change to master
