### ISSUE TITLE
google java codestyle is not used

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#167]
According to Developer Guide (http://www.opendevstack.org/doc/development-guide) , the source code has to be formated with **Google Java Codestyle**.

This is not the case in many files.

Examples
- Block indentation: (https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation)
> Each time a new block or block-like construct is opened, the indent increases by two spaces. When the block ends, the indent returns to the previous indent level. The indent level applies to both code and comments throughout the block

- Nonempty blocks: K & R style: (https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style)
> Braces follow the Kernighan and Ritchie style ("Egyptian brackets") for nonempty blocks and block-like constructs:
- No line break before the opening brace.
- Line break after the opening brace.
- Line break before the closing brace.
- Line break after the closing brace, only if that brace terminates a statement or terminates the body of a method, constructor, or named class. For example, there is no line break after the brace if it is followed by else or a comma.

**Comment by ungerts** [comment]
@stefanlack do you also plan to check code style in the Travis build?

**Comment by stefanlack** [comment]
@ungerts : not yet, but good idea. Created #169
