### ISSUE TITLE
authentication via oauth2

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#170]
Provision App should allow authentifaciton via ouath2 and get user roles from id provider.

**Comment by stefanlack** [comment]
I am working on this. Our current implementation is based on the code from Pull Request https://github.com/opendevstack/ods-provisioning-app/pull/164

**Comment by clemensutschig** [comment]
@stefanlack  - you are on latest of the PR, right? any issues encountered?

**Comment by stefanlack** [comment]
@clemensutschig Yes, i am.
Issues: i will write in some remarks in the PR
