### ISSUE TITLE
fe-angular quickstarter fails with certain names (fe-angular-7)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#175]
08:22:22 | + echo 'generate project'
-- | --
08:22:22 | + sudo docker run --rm -v /tmp/rundeck_560954ef-d245-456c-9460-6c592c9d7784_870:/data ng new fe-angular-7 --style=scss --skip-git --skip-install
08:22:24 | Project name "fe-angular-7" is not valid. `New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.`
08:22:24 | fe-angular-7

**Comment by tjaeschke** [comment]
Maybe we should rethink the component default naming. For angular a numeric value at this position isn't allowed, but for others it is.

**Comment by michaelsauter** [comment]
@adyachok Could you maybe look into adding a validation for this in the prov app?

**Comment by adyachok** [comment]
@michaelsauter yes I will take a look on it

**Comment by stitakis** [comment]
@michaelsauter @adyachok is this actual? Asking because we have done some changes in ProvApp that allow only valid openshift names #281 and #355

**Comment by stitakis** [comment]
@michaelsauter @adyachok it is actual... I did a quick test to reproduce the problem... problem is that ng new fe-angular-7` fails because the name is invalid:
```
+ ng new fe-angular-7 --style=scss --skip-git --skip-install
Project name "fe-angular-7" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.
fe-angular-7
```
Quick fix would be to restrict more components names by disallowing numbers.

Adding quickstarters specific name validation rules would be more work and I don't think we could added in ODS 3.0 release.

**Comment by clemensutschig** [comment]
folks there is a PR .. opendevstack/ods-provisioning-app#234  from @adyachok

**Comment by michaelsauter** [comment]
To get this issue fixed for 3.0, I suggest to go with @stitakis proposal to disallow numbers.

In my eyes, we should not pursue the approach chosen in PR #234:

- it is quite complex for a small feature
- it puts knowledge of the quickstarters into the prov-app, which is not ideal: we spent quite some effort to make the prov app "quickstarter agnostic"

Of course, disallowing numbers might look limiting at first, but then maybe we can just wait to see how many people complain. And then we would need to weight that against the effort of building validation logic that is based on rules defined by each quickstarter ...

@clemensutschig @stitakis @adyachok @oalyman Agreed?

**Comment by stitakis** [comment]
@michaelsauter I agree to disallow numbers... this should be implemented in the UI and in corresponding endpoint in the back-end.

**Comment by netzartist** [comment]
FYI an [explanation](https://github.com/angular/angular-cli/issues/3816#issuecomment-327006452) why Angular CLI is so restrictive to that.

So, the regex should then be this, right?

`(([A-Za-z][-A-Za-z_]*)?[A-Za-z]){3,40}`
