### ISSUE TITLE
Authorization on provisioning app

### ISSUE THREAD

**Issue by alanbort** [opendevstack/ods-provisioning-app#177]
Authorization for basic prov-app use should be tied to all the "-MANAGER" groups instead of a single, dedicated group.

The current implementation requires two steps:
1. get access to prov-app
2. become -MANAGER for a project to be able to view/provision to it on prov-app

All -MANAGERs should be granted access by default without need for any extra steps

**Comment by rattermeyer** [comment]
without context, this seems to be company specific. Can we restate the requirement, so it fits the opensource project?

**Comment by stefanlack** [comment]
@alanbort :
can you please specify further details regarding this issue? Thanks.
