### ISSUE TITLE
Remove Spring MVC

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#179]
We should refactor the provisioning app and part it to a SPA and an API Backend, which can be handled stateless, only with tokens. So we can run the frontend and the backend in different zones and contextes, for example an API only version for shop systems, where no frontend is needed.

**Comment by stefanlack** [comment]
While splitting beween backend and frontend is usefull, I see not why whe should remove Spring MVC at all.
See also #194, which want to split frontend in two parts (creating projects and modify ) project
