### ISSUE TITLE
Add Update guide

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#18]
Add section to documentation how to update between releases or update to HEAD

**Comment by michaelsauter** [comment]
@tjaeschke A general update section is in the PMC / CONTRIBUTING.md. I guess that should be moved to a better place, and extended with the info for the prov app?

**Comment by clemensutschig** [comment]
I suggest we put this into the readme.md of prov App..  thoughts? I need to write it up for our prod cluster as well..

**Comment by michaelsauter** [comment]
This related to https://github.com/opendevstack/PMC/pull/8.

**Comment by michaelsauter** [comment]
This will be documented in the general update guide.
