### ISSUE TITLE
adding new modul to existing project creates empty repository

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#183]
Steps :

1. Choose _Modify existing project_
2. Select project
3. Select at least one quickstarter to add.
4. Start provisioninig

Result:
- new bitbucket repository was created
- *But* repository is empty

**Comment by clemensutschig** [comment]
@stefanlack  - please check logs and rundeck. both will give you the error!

**Comment by stefanlack** [comment]
@clemensutschig yes, indeed. 
Rundeck Job _fe_angular_ Failed with

> WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Error response from daemon: name unknown
Error response from daemon: No such image: docker-registry-default.192.168.56.101.nip.io/cd/jenkins-slave-nodejs10-angular:latest
Sending build context to Docker daemon  26.11kB
Step 1/6 : FROM cd/jenkins-slave-nodejs10-angular
pull access denied for cd/jenkins-slave-nodejs10-angular, repository does not exist or may require 'docker login'
Result: 1
Failed: NonZeroResultCode: Result code was 1

**Comment by clemensutschig** [comment]
did you install / build
https://github.com/opendevstack/ods-project-quickstarters/blob/master/jenkins-slaves/nodejs10-angular/ ?

that would give you the slave :)

**Comment by stefanlack** [comment]
Ah, @tjaeschke  told me that I have to build the jenkins slaves via caling

> vagrant ssh openshift -c "sudo /ods/ods-core/infrastructure-setup/scripts/prepare-jenkins-slave-builds.sh"

Let's wait until they are build and test again.

**Comment by stefanlack** [comment]
Thank you, @clemensutschig .

**Comment by stefanlack** [comment]
Error was related to missing jenkins notes. 
Retest: angular frontend is provisioned again.

Anyway: i found a smal bug in the logging of ProjektApiController, see https://github.com/opendevstack/ods-provisioning-app/pull/184
