### ISSUE TITLE
refused bequest on IServiceAdapter.getProject?

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#186]
Some implementations of org.opendevstack.provision.adapter.IServiceAdapter are not implementing _getProjects(String filter)_:

- org.opendevstack.provision.services.BitbucketAdapter#getProjects
- org.opendevstack.provision.services.ConfluenceAdapter#getProjects
- org.opendevstack.provision.services.RundeckAdapter#getProjects

Only these classes actual implemented getProjects:
- org.opendevstack.provision.services.StorageAdapter#getProjects
- org.opendevstack.provision.services.JiraAdapter#getProjects

While implementation of those methods is easy (in fact I have already implemented some of them)... why also _org.opendevstack.provision.services.CrowdProjectIdentityMgmtAdapter_ implements _IServiceAdapter_?

Current implementation of _CrowdProjectIdentityMgmtAdapter.getProjects_:

`  @Override
  public Map<String, String> getProjects(String filter) {
    return new HashMap<>();
  }`

**Comment by clemensutschig** [comment]
@stefanlack  - because it's s a service adapter as well :)

**Comment by stefanlack** [comment]
Issue name should be left on 'bequest', as defined - for example in https://refactoring.guru/smells/refused-bequest

**Comment by stefanlack** [comment]
Internal code quality seams not to be at highest priority in the current state of the project. Therefore, I close this issue for now.
We can re-open this in case we decide to do a bigger refactoring / cleanup of provisioning app.
