### ISSUE TITLE
Scanning of Sources in travis build

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#187]
Beside checking codestyle, we could run sonar scans on the code as well.
Sonarcloud is free for open source projects.

* https://sonarcloud.io/about
* https://docs.travis-ci.com/user/sonarcloud/

**Comment by clemensutschig** [comment]
Coool.. lets do

**Comment by stitakis** [comment]
btw... we can add snyk scan to travis bulid #269

**Comment by michaelsauter** [comment]
This is not releated to a particular release, hence taking of from release 2.

**Comment by stitakis** [comment]
I'm closing this as we are using github actions to build the provisioning app.
