### ISSUE TITLE
provisioning app fails if Active directory groups does not exists.

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#192]
**ODS Version**:1.x

**Error**:
```
Could not PUT > https://xxxxxxxxx/rest/api/1.0/projects/XXXXXX/permissions/groups?permission=PROJECT_WRITE&name=GROUP_FAKE_NAME-TEAM :

 {errors:[{context:null,message:No such groups: GROUP_FAKE_NAME-TEAM,exceptionName:null}]} Errorcode: 404`
```
We have an automated process that create the AD groups and then execute prov-app API to create the project and assign permissions.

This error is caused because the group is not already sync on Jira/BB/Confluence instance,

I suggest before try to create the project and assign permissions, check if the system is in the required state(The group exist in jira/bb/confluence) before try to apply the creation of the project.
This help us to minimize the amount of inconsistent created projects.
and we can retry the creation of the project until the group exist.

**Comment by clemensutschig** [comment]
Solved in 1.2 .. retry is a Bad thing here because of thread/Session timeout.

We cannot Port  this back because ist Part of a massive refactoring change...

**Comment by segator** [comment]
nice to hear this!

So then what is the behaviour of prov app to handle groups not yet sync?

**Comment by clemensutschig** [comment]
this is done (in 1.2) . nothing will be created - and any resources that were created are rolled back.
