### ISSUE TITLE
Split provisioning app?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#194]
When discussing opendevstack/ods-project-quickstarters#283, the following idea emerged:

* Have one central provisioning app which can ONLY provision new projects
* Extract the functionality to create components within the project to a specialised, per-project provisioning app (potentially part of the webhook proxy). That way, the authentication to create components can be done via OpenShift, which already solves the auth/permission problems.

**Comment by gerardcl** [comment]
anyway, I see it related somehow in terms of implementation if this idea proceeds, or?

**Comment by clemensutschig** [comment]
@michaelsauter - ods2 and wont fix or?

**Comment by michaelsauter** [comment]
Yes we can close this. Maybe we revisit it when we think about possible provisioning app refactors, but the solution will likely look different.
