### ISSUE TITLE
Provisioning is allowed even when Openshift project is not created

### ISSUE THREAD

**Issue by smolanet** [opendevstack/ods-provisioning-app#195]
If you have an ATLASSIAN project without Openshift, you can select a quickstarter and click on "Start provision".
It looks like the task is running but actually the Proviosioning job field is empty:
![image](https://user-images.githubusercontent.com/37191037/64556079-02823980-d33f-11e9-9617-6fbe9cfcd6c9.png)
In addition, after closing the window, if you select the project again, it shows as the quickstarter has been successfully deployed:
![image](https://user-images.githubusercontent.com/37191037/64556150-2776ac80-d33f-11e9-9855-d098a4a77d87.png)

**Comment by clemensutschig** [comment]
hmmm - if you have the rights - the project will be upgraded automatically. 
@smolanet  what happened in your case?

**Comment by smolanet** [comment]
yes, there is https://bitbucket.biscrum.com/projects/VMP
nothing was created there

**Comment by clemensutschig** [comment]
@smolanet  - shit, I can repro it ... good catch .. debugging right now :)
