### ISSUE TITLE
URL already taken error provisioning quickstarter after Authentication failed

### ISSUE THREAD

**Issue by smolanet** [opendevstack/ods-provisioning-app#227]
If you click on Start provision after session is expired, you receive an Authentication failed error:
![image](https://user-images.githubusercontent.com/37191037/65163875-15ca8e80-da3c-11e9-8f9a-696f9e15bb67.png)
After log in again, if you try to provision again the quickstarter using the same name, you receive another error as the URL is already taken:
![image](https://user-images.githubusercontent.com/37191037/65163996-4b6f7780-da3c-11e9-8748-cf938f1ae7d2.png)

**Comment by clemensutschig** [comment]
This is fixed in 1.2
