### ISSUE TITLE
Antorra docs need to be updated with latest master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#245]
**Describe the bug**
Masters Readme is ahead of antorra docs

@tjaeschke fya

**Comment by stefanlack** [comment]
@clemensutschig  the content of https://github.com/opendevstack/ods-provisioning-app/blob/master/README.md is not shown at the page https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/index.html.

Page https://www.opendevstack.org/ods-documentation/common/latest/documentation.html explains, how the antorra documentation is build:

> The documentation is contained in the doc subdirectory of every project. Every doc directory is the root of an Antora Component. We have additional projects containing the playbook and the UI customization.

I will move / merge the content from the Readme.md file to right place at https://github.com/opendevstack/ods-provisioning-app/blob/master/docs/modules/ROOT/pages/index.adoc and I will take care, that no information is duplicated between these locations. 

Finaly, if will add a short text / link to the new documentation location.

**Comment by stefanlack** [comment]
Done. https://github.com/opendevstack/ods-documentation/pull/12
