### ISSUE TITLE
Setting of Java executables on slaves

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#248]
**Describe the bug**
Jenkins Slaves problems on CentOS with alternatives approach.
e.g. configure-slave:
$(alternatives --display javac | awk '/family.*x86_64/ { print $1; }')

tries to execute the evaluated string

**To Reproduce**

$(alternatives --display javac | awk '/family.*x86_64/ { print $1; }')

will result in:
error: invalid flag: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/bin/javac
Usage: javac <options> <source files>
use --help for a list of possible options

**Expected behavior**

corrected 

**Screenshots**

**Affected version (please complete the following information):**
 - OKD: 3.11
 - OpenDevStack 1.1

**Additional context**
We have CentOS / OKD in use.

**Comment by stitakis** [comment]
I think this is actual anymore. I'll close it
