### ISSUE TITLE
Update antora version tag on 1.2.x branch

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#252]
**Is your feature request related to a problem? Please describe.**
Adding branch 1.2.x to ods-documentation/site.yml results in "duplicate nav: latest@common:ROOT:nav.adoc"

**Describe the solution you'd like**
Update the version description tag in the 1.2.x branch to 1.2.x in the docs/antora.yml

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by clemensutschig** [comment]
https://www.opendevstack.org/ods-documentation/ods-provisioning-app/1.2/index.html 

shows 1.1 related info ... where is all the new stuff we added (e.g. the API that changed)?

**Comment by rattermeyer** [comment]
Good question. Thought that @stefanlack migrated this to https://github.com/opendevstack/ods-provisioning-app/blob/master/docs/modules/ROOT/pages/index.adoc. 
We need to double check.

**Comment by rattermeyer** [comment]
hmm. the index is only one part. the README.md was split up into different parts. everything should be there. see: 
[Overview](https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/index.html)
[Configuration Guide](https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/configuration.html)
[Internal architecture](https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/architecture.html)
[FAQ](https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/faq.html)
and [upgrade notes](https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/upgrade_notes.html)
All listed on the left navigation panel.
Think the structure helps instead of having a really long file.

**Comment by clemensutschig** [comment]
offencing commit  
https://github.com/opendevstack/ods-provisioning-app/commit/efcbf4fc9390a1aef6547245e4903ea0b755c142#diff-04c6e90faac2675aa89e2176d2eec7d8

curl requests gone :(

**Comment by rattermeyer** [comment]
You are note referencing the curl requests, as documented here: https://www.opendevstack.org/ods-documentation/ods-provisioning-app/1.2/index.html#_using_the_provision_application_via_api_thru_direct_rest_calls

**Comment by stefanlack** [comment]
@clemensutschig curl requests are still present. Please see

https://github.com/opendevstack/ods-provisioning-app/blob/master/docs/modules/ROOT/pages/index.adoc#using-the-provision-application-via-api-thru-direct-rest-calls

and https://www.opendevstack.org/ods-documentation/ods-provisioning-app/1.2/index.html#_using_the_provision_application_via_api_thru_direct_rest_calls

![image](https://user-images.githubusercontent.com/2901438/66731783-52ca4b00-ee59-11e9-885c-725876dcf5cf.png)

**Comment by stefanlack** [comment]
@clemensutschig can you please give additional information, if something is missing?

Please note that [README.md](https://github.com/opendevstack/ods-provisioning-app/blob/master/README.md) now only has references to the documentation inside the _docs_ folder and the antora documentation site.
