### ISSUE TITLE
Missing .gitattributes

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#257]
**Describe the bug**
We are developing on different platforms (Linux / Windows / Mac).
This can cause inconsistensies in line endings when commiting changes.

**Expected behavior**
The line endings in the repo should always be LF to be consistent with the other ODS repos.

**Solution**
Introduce a .gitattributes as we maintain for other repos as well, so we do not rely on a git installation configured correctly for multi-platform development

**Comment by rattermeyer** [comment]
solved by #258

**Comment by rattermeyer** [comment]
yes, see opendevstack/ods-project-quickstarters#415

**Comment by michaelsauter** [comment]
@rattermeyer Why are only `.sh` files set to `LF`? Shouldn't we have all files be `LF`?

**Comment by rattermeyer** [comment]
Because .sh files need to be checked out on Windows as LF as well (if you e.g. you cygwin to execute sh files). It is because they might be "executed" on Windows as well.
The other part is handled as proposed by [github](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings)
