### ISSUE TITLE
STORAGE_CLASS_DATA is undefined per default but tailor requires STORAGE_CLASS_DATA to be set

### ISSUE THREAD

**Issue by kiwo** [opendevstack/ods-provisioning-app#262]
Hi, i am not shure if this is an issue with tailor or with the generation of the default config or with the template. When setting up ODS from scratch the autogenerated config STORAGE_CLASS_DATA="" results in the following error:

![image](https://user-images.githubusercontent.com/16405776/68198962-5f0b7900-ffbd-11e9-9f20-33da0cf8f841.png)

**Comment by michaelsauter** [comment]
Does https://github.com/opendevstack/ods-configuration-sample/pull/44 solve the issue? Or is the problem that there must be a value for that key?

**Comment by kiwo** [comment]
an empty string results in the same error. this is fixed in upcoming ods-core ocp-templates by setting required: false

**Comment by michaelsauter** [comment]
@kiwo Can we close this issue?

**Comment by clemensutschig** [comment]
@kiwo?

**Comment by michaelsauter** [comment]
Fixed now.
