### ISSUE TITLE
Prov App Quickstarter configuration

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#270]
In #265, the temporary solution to configure quickstarters is this snippet in the `application.properties` file:
```
jenkinspipeline.quickstarter={beSpringBoot: 'http://192.168.56.31:7990/scm/prov/quickstarter-jenkins.git#master/beSpringBoot/Jenkinsfile'}
jenkinspipeline.create-ods-projects-job=http://192.168.56.31:7990/scm/opendevstack/ods-core.git#production/create-projects/Jenkinsfile
```
To allow this behaviour, the webhook proxy was altered to accept a URI for a repository.

This is not good because:
* It contains IP adresses
* It allows to execute arbitrary code when someone is able to bypass security e.g. on the webhook proxy

Therefore, we will not have this solution for ODS. PR https://github.com/opendevstack/ods-core/pull/231 already adjusted the webhook proxy to revert the "full URI" changes, and instead offers the users of the `/build` endpoint to specify a project to use.

As a consequence, PR #265 must be altered to:
* allow to configure only project, repository, branch and jenkinsfile path
* make a request to the webhook proxy which includes the project field in the payload

A new example `application.properties` might look like this:
```
jenkinspipeline.quickstarter={beSpringBoot: 'prov/quickstarter-jenkins.git#master/beSpringBoot/Jenkinsfile'}
jenkinspipeline.create-ods-projects-job=opendevstack/ods-core.git#production/create-projects/Jenkinsfile
```

**Comment by clemensutschig** [comment]
If fixed in ods 2 - Please close

**Comment by michaelsauter** [comment]
This is done.
