### ISSUE TITLE
Creating Secret/cd-user-with-password failed

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#273]
**Describe the bug**
Wenn running tailor update for provisioning app:
```
Creating Secret/cd-user-with-password ... failed
2019/11/19 13:36:15 Update aborted: Error from server (BadRequest): error when creating "STDIN": Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 2, error found in #10 byte of ...|:"cd_user"},"kind":"|..., bigger context ...|a":{"password":"Y2RfdXNlcg==","username":"cd_user"},"kind":"Secret","metadata":{"annotations":{},"la|...

```
tailor cannot create credentials.

**To Reproduce**
1. exeute prepare-provisioning-app.sh

**Expected behavior**
Credential secrets for cd_user have been created.

**Affected version (please complete the following information):**
 - Branch master, following the  local installation guide.

**Log Output**
```
cd ${BASE_DIR}/ods-provisioning-app/ocp-config/prov-cd
yes 'y' | tailor update serviceaccount,pvc,dc,rolebinding,route,secret,svc --force
```

**Additional context**

**Comment by michaelsauter** [comment]
@stefanlack Will look into it. Base64 related.

**Comment by stefanlack** [comment]
@michaelsauter thank you. As far as I see, username has to be base64 encoded. I already testet this locally. But somehing else seams to be incorrect, since the my jenkins build still cannot checkout.

**Comment by michaelsauter** [comment]
@stefanlack Created a fix - see PR. If it still does not work, maybe the syncing has not happened yet?
