### ISSUE TITLE
invalid rolebinding.yml

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#276]
**Describe the bug**
When ods-core/infrastructure-setup/scripts/prepare-provisioning-app.sh is executed in openshift,
the creation of role bindings fails

**To Reproduce**
1. Run script on openshift vm via `vagrant ssh openshift -c "sudo /ods/ods-core/infrastructure-setup/scripts/prepare-provisioning-app.sh"`

**Log**
```
Patching RoleBinding/jenkins_edit ... failed
2019/11/21 09:21:59 Update aborted: Error from server: converting (v1.RoleBinding).[0].Kind to (rbac.RoleBinding).[0].Kind: APIGroup not present in src
```
**Expected behavior**
Rolebinding was created

**Screenshots**
![image](https://user-images.githubusercontent.com/2901438/69328253-35a24c80-0c4f-11ea-8ffc-590adf04f2eb.png)

**Affected version (please complete the following information):**
 - OpenShift: [e.g. 3.9, 3.11]
 - OpenDevStack based on master

**Comment by michaelsauter** [comment]
@stefanlack Check if you have the latest Tailor version, in `0.10.3` I'm trimming `userNames` and `groupNames` because they are only for legacy clients.

**Comment by stefanlack** [comment]
@michaelsauter Tailor in my openshift virtual box is old,  0.9.5. We need to update the local installation script.

**Comment by michaelsauter** [comment]
@stefanlack Yes, I will do that ... there might be another patch release though before v2.
