### ISSUE TITLE
job instance information at provision result page is missing

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#279]
**Describe the bug**
After provisioning, the application page contains the text "Provisioniong jobs:null"
The url to the jenkins job has to be added

**Screenshots**
![image](https://user-images.githubusercontent.com/2901438/69529032-bc1c9e00-0f6f-11ea-8414-2f95ad1b57c3.png)

**Affected version**
 -Current version, based on master branches

**Comment by stefanlack** [comment]
@michaelsauter should we delete this block or should we  add a link zu the jenkins job instead?

**Comment by clemensutschig** [comment]
Jenkins job instance

Stefan Lack <notifications@github.com> schrieb am Mo., 25. Nov. 2019, 10:45:

**Comment by stefanlack** [comment]
https://github.com/opendevstack/ods-core/issues/281 would be helpful for implementing this feature.

**Comment by michaelsauter** [comment]
I tested this just now, and while the link works, it does not display the full URL. For consistency, should we disaply the full URL? So with `https://jenkins....` in front?

**Comment by stefanlack** [comment]
@michaelsauter I decided to display the jobname instead of the url, because the url get's pretty long and ugly. For case of component creating, one can select multiple quickstartes at one time. Displaying all urls for every component causes formatting problems.

We can easily change it back to the old behaivor in
https://github.com/opendevstack/ods-provisioning-app/blob/612b1c06315089c2ff1898981f00116cebde8cf4/src/main/resources/static/js/client.js#L401

to `html += "<a href='" + job.url +"' target='_blank'>" + job.url+"</a></br>";`

But should we?

**Comment by michaelsauter** [comment]
Hmm maybe you are right with the long URL. Let's leave it like it is.
