### ISSUE TITLE
Component Names : Only allow valid labels

### ISSUE THREAD

**Issue by akhilsoman** [opendevstack/ods-provisioning-app#281]
**Describe the bug**
Provisioning app should reject component names that doesn't fit the Kubernetes label Syntax standards. 

Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

**Expected behavior**
Provisioning app should not allow users to enter invalid component labels.

**Additional context**
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by stitakis** [comment]
and update on this... change is almost done and test. I'll create a PR soon
