### ISSUE TITLE
Web UI / CURL gets 504 Gateway timeout after 30s during provisioning of quickstarters / projects ..  

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#29]
reproduces via API as well

19), continuing anyway.
* STATE: PROTOCONNECT => DO handle 0x66f160; line 1596 (connection #0)
} [5 bytes data]
> POST /api/v1/project HTTP/1.1
> Host: prov-app-test.....
> User-Agent: curl/7.58.0
> Accept: */*
> Cookie:  JSESSIONID=..; crowd.token_key=....
> Content-Type: application/json; charset=utf-8
> Content-Length: 352
>
} [352 bytes data]
* upload completely sent off: 352 out of 352 bytes
* STATE: DO => DO_DONE handle 0x66f160; line 1658 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x66f160; line 1783 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x66f160; line 1799 (connection #0)
100   352    0     0  100   352      0     11  0:00:32  0:00:30  0:00:02     0{ [5 bytes data]
* HTTP 1.0, assume close after body
* Marked for [closure]: HTTP/1.0 close after body
< HTTP/1.0 504 Gateway Time-out
< Cache-Control: no-cache
< Connection: close

**Comment by stitakis** [comment]
Hi, 
the class org.opendevstack.provision.util.RestClient creates a http client with a timeout of 30 secs (see line 41: int connectionTimeout = 30);
I think, this might be causing the observed ConnectionClosedException in ods-provisioning-app.

**Comment by clemensutschig** [comment]
implemented on premise as test -> works! ... finally
