### ISSUE TITLE
Quickstarters are not populated

### ISSUE THREAD

**Issue by maierl** [opendevstack/ods-provisioning-app#293]
From time to time, the prov-app breaks. The list of quickstarters that can be added to a project is empty and all existing ones are denoted as "undefined".

![image](https://user-images.githubusercontent.com/8655419/69964066-e2af7b80-1511-11ea-9140-cdd88d4dc7dd.png)

**Comment by michaelsauter** [comment]
@maierl I think that might be due to session timeout with Rundeck. If this is the case, it'll go away automatically with ODS 2.

**Comment by maierl** [comment]
Is there a way for me to work around this with the current version? Re-login in pro-app does not fix the issue. Like this, I cannot provision anything and I don't know when it will be possible again.

**Comment by clemensutschig** [comment]
restart of the application will help.. though we cannot pinpoint really what is the issue?! :(

**Comment by michaelsauter** [comment]
Quickstarters are not loaded from Rundeck anymore in ODS 2, therefore I'll close this.
