### ISSUE TITLE
upgrade to ODS 2 : For projects created via rundeck "Current Quickstarters" column shows undefined

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-provisioning-app#300]
**Describe the bug**
For projects created via rundeck "Current Quickstarters" column shows `undefined`.

"Current Quickstarters" column data is created via "enhancing" the historical project content from the json files.
This is done by using the component_type of the stored json and then mapping it to the name/id (see [ProjectApiController.java](https://github.com/opendevstack/ods-provisioning-app/blob/2dbc710231d94dea94d915b2f7b447b9a970f68c/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L460)) of the configured quickstarters (see [application.properties](https://github.com/opendevstack/ods-provisioning-app/blob/2dbc710231d94dea94d915b2f7b447b9a970f68c/src/main/resources/application.properties#L114))

For projects created via rundeck the component_type is a uuid (see [be-docker-plain.yaml](https://github.com/opendevstack/ods-project-quickstarters/blob/dbac2ed093dc7e159acd84d9d482728499fb4c25/rundeck-jobs/quickstarts/be-docker-plain.yaml#L5)) and thus the "enhancing" for those projects fails.
To make it work there needs to be a mapping between the old uuids and the new names/ids.

**To Reproduce**
Open a project created via the legacy rundeck implementation

**Expected behavior**
Show the correct data in the "Current Quickstarters" column for old projects as well

**Screenshots**
![image](https://user-images.githubusercontent.com/590132/70085075-d9a4d400-160f-11ea-9dfb-62d899a06f46.png)

**Affected version (please complete the following information):**
 - OpenDevStack 2.x

**Comment by clemensutschig** [comment]
Must fix for 2.0... the Good news is we can hardcode the uuid..

**Comment by clemensutschig** [comment]
enhancement with original UUIDs ... needs to be in
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java#L106 

as they are static and are on github - we can just add them, or build a sidecar file .. @oalyman - can you take this up
