### ISSUE TITLE
prov-app improvements ideas

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#325]
**migrate to golang:**
* Reduce memory footprint
* increase start speed (This will allow a proper scale to zero)
* be prepared for possible transformation to OCP Operator.

**What if we can do prov-app stateless?**
an Idea: create adapter to support state to configmaps, this will allow scalability and open a possible future to create an ODS Operator for OCP.

Right now prov-app is keeping project configuration in json files in the PVC that we need to edit manually in case provisioning fails.

**Comment by stitakis** [comment]
Hi @segator, a couple of thoughts on this item:

Regarding "migrate to golang":
- currently we are not suffering runtime problems (or at least I'm not aware), therefore, I don't see necessity to reduce memory footprint or increase start speed. Although both things are always a good thing to do. both could be addressed in java too.
- there is also support of OCP operator framework for java
So I don't see the need or benefit of a migration to golang.

Regarding "do prov-app stateless":
- I do not get the part of "create adapter to support...", can you please elaborate a bit more?
- "prov-app is keeping project configuration": I see here also room for improvement. One of prov-app role is to deploy to openshift... so it imho it should take the list of existing projects from there. The json file could be kept for audit purposes.

Probably I'm missing something... therefore I 'd like to understand more in detail your requirements... happy to chat with you about it.

**Comment by metmajer** [comment]
Same here, Java vs. Golang is not our issue. Since the service will soon run as a singleton, this doesn't make a difference given there will be dozens of applications running dozens of components each implemented in Java.

@segator The issues lie more in the stability of the service and processing breaking, correct? Please focus on elaborating on those. Thanks!

**Comment by metmajer** [comment]
@segator please close the issue if you agree. Thanks!
