### ISSUE TITLE
Improve code readability / Variable Names

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-provisioning-app#326]
The overall code is a little bit hard to understand, but we could start improving small pieces like:

Distinguishing variables in the same class not only by a simple upper case:
https://github.com/opendevstack/ods-provisioning-app/blob/bcd75037b1e6d81d2bbe27f8ccdc47ab8c53751d/src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java#L19

https://github.com/opendevstack/ods-provisioning-app/blob/bcd75037b1e6d81d2bbe27f8ccdc47ab8c53751d/src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java#L23-L27

And following some java naming conversions, like for enums which should have all values in UPPER_SNAKE_CASE:

https://github.com/opendevstack/ods-provisioning-app/blob/bcd75037b1e6d81d2bbe27f8ccdc47ab8c53751d/src/main/java/org/opendevstack/provision/config/QuickstarterType.java#L3-L6

**Comment by stitakis** [comment]
I'll close this as we are achieving technical debt in  #638
