### ISSUE TITLE
prov-app preflight check

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#330]
**Check Before create project**
* Return an error code/message  on the API when jira user used to create project doesn't have apropiate permissions to  create/update/rollback(delete) project
* Return an error code/message  on the API when jira user/groups injected in the API doesn't exists. This case should return an especial code because we can implement a retry in the system that call prov-app API, because in our case groups are created in the same pipeline but sincronized to jira in async way, 

This should apply to jira, confluence and bitbucket.

**Comment by stitakis** [comment]
update on this... this is a complex change. I have done some progress and will provide a WIP for early review soon

**Comment by stitakis** [comment]
to this change will follow 3 more PR:
- pre flight checks for Jira
- pre flight checks for Confluence
- change of some API endpoints to return json instead of text

**Comment by stitakis** [comment]
Current open tasks to complete this:
- confluence pre flight checks need to be implemented
- backport to 2.x needs to be done
- integration test needs to be completed
