### ISSUE TITLE
provisioning of quickstarters fails if pod name label is longer than 63 characters

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-provisioning-app#335]
**Describe the bug**
Component provisioning fails when starting the pipeline if Kubernetes pod label too long (limit is 63).

**To Reproduce**
1. In ODS 2.x/master, go to provisioning app and provision `be-typescript-express` component
2. Jenkins provisioning fails

**Expected behavior**
 The component should be provisioned without issues

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: master, 2.x (might be any version)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```bash
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/jobs/newproject-cd/jobs/newproject-cd-ods-quickstarter-be-typescript-express-be-typescript-express-2x/workspace
[Pipeline] {
[Pipeline] }
[Pipeline] // node
[Pipeline] podTemplate
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: Labels must follow required specs - https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set: quickstarter-be-typescript-express-ods2test3-be-typescript-express
Finished: FAILURE
```

**Additional context**
We need to assure pod labels are no longer than 63 characters.

**Comment by michaelsauter** [comment]
Proposed solution:

1. Shorten name of Jenkins pipeline to be `ods-qs-$COMPONENT_ID`
2. Ensure `$COMPONENT_ID` is less than 40 characters

**Comment by stitakis** [comment]
@michaelsauter should we add a minimal length validation too? 5 chars?

**Comment by michaelsauter** [comment]
Minimal length sounds good, but I would do 3 chars. E.g. `app` should be valid I think.

**Comment by stitakis** [comment]
@michaelsauter fine... I'll add validation rule for a min length to 3 chars
