### ISSUE TITLE
Provisioning fails for some quickstarters when component ID is the same as the component type

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#336]
**Describe the bug**
When the type of the component is used for the component name (ID), some quickstarters might fail. See https://github.com/opendevstack/ods-quickstarters/issues/117.

**To Reproduce**
1. Go to prov app
2. Add quickstarter using the component type as name (e.g. `fe-react`)
3. See error

**Expected behavior**
Should be prevented, users must enter proper name.

**Affected version:**
 - OpenDevStack: 2.x, master

**Comment by gerardcl** [comment]
same for `fe-angular`, at `init Project` stage in the provisioning job:
```bash
+ ng new fe-angular --style=scss --skip-git --skip-install
ERROR! fe-angular/README.md already exists.
```

**Comment by michaelsauter** [comment]
Proposed quick fix:

1. Do not allow component ID to be same as component type
1. Don't default to component type. Make field empty so that people come up with a proper name. Make sure name cannot be blank either when submitting :)
