### ISSUE TITLE
Release the provisioning app as docker image

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-provisioning-app#337]
**Is your feature request related to a problem? Please describe.**
Currently, I have to clone the repo of the provisioning app and build it locally / in my ods cluster to have a running instance of the application.
This is cumbersome and costs a lot of time if I am only interested in running an instance of it.

**Describe the solution you'd like**
It would be nice if every version of the provisioning app would be released as a docker image.
This would drastically cut down the time for having it running.
Moreover, it would make it easier to compare installations on different sites.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by sino92** [comment]
Solution helps solve this too: https://github.com/opendevstack/ods-provisioning-app/issues/327

**Comment by michaelsauter** [comment]
@sino92 How so?

**Comment by sino92** [comment]
This issue would be the prerequisite to provision the provisioning app. Then the user can specify persistent volume location as an environment variable.

**Comment by stitakis** [comment]
@oalyman this was done for ODS 3.x. I'll close it. Please reopen if I'm wrong!
