### ISSUE TITLE
Documentation of quickstarter configuration

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-provisioning-app#338]
Hi,

Changelog includes notes that Rundeck was replaced with Jenkinspipelines.
Documentation doesn't include this update. How to integrate a new Quickstarter into the provisioning-app isn't really documented or I wasn't able to find it :-| .

See, e.g.
https://github.com/opendevstack/ods-provisioning-app/blob/master/docs/modules/ROOT/pages/index.adoc

Thanks

**Comment by clemensutschig** [comment]
@tbugfinder  - hugh ....

https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-app/cm.yml#L143

:)

we have to fix the doc though .. scary (@michaelsauter )

**Comment by michaelsauter** [comment]
Yes docs need fixing. Will include for 3.0.

**Comment by clemensutschig** [comment]
@tbugfinder  - can you also take a stab at this?

**Comment by michaelsauter** [comment]
Depends on outcome of #363.
