### ISSUE TITLE
Provision app removes existing project (when existing name / key is passed to "addProject" API)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#345]
**Describe the bug**
in case a new project is created /with a different key but an *existing* name - the provision app will remove the existing project (Note/Attention: this happens only if *provision app is used thru API* and not thru the UI/frontende)

**To Reproduce**

**Expected behavior**
Error message that a project with this key / name already exists

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [2.0]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.p.c.ProjectApiController - An error occured while creating project [AHR], reason [Could not POST > htt
ps://jira.biscrum.com/rest/api/latest/project : {"errorMessages":[],"errors":{"projectName":"A project with that name already exists.","projectKey":"Project 'A....' uses this project key."}} Errorcode: 400] - but all cleaned up!
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.provision.util.rest.RestClient - Call failed: 
org.opendevstack.provision.util.exception.HttpException: Could not GET > https://x.y.z/rest/api/latest/project/AHR/permissionscheme : {"errorMessages":["No project 
could be found with key 'AHR'."],"errors":{}} Errorcode: 404
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.provision.services.JiraAdapter - Could not clean up jira project permission set AHR error: Could not G
ET > https://x.y.z/rest/api/latest/project/AHR/permissionscheme : {"errorMessages":["No project could be found with key 'AHR'."],"errors":{}} Errorcode: 404
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] DEBUG o.o.provision.services.JiraAdapter - Cleanup done - status: 0 components are left ..“
```

**Additional context**
This is a major bug - introduced with cleanup (in 2.o)

https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L155
throws an exception that is caught at 
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L198
which causes rollback / delete

**Comment by clemensutschig** [comment]
Quick RCA so people can follow.

- with ODS 2.0 we introduced rollback (to ensure no resources are left over in case we cannot provision components /e.g. repo across the federated stack)

- this functionality sits largely in ProjectAPIController/addProject - and is triggered up catching any exception. 
- in the case a project exists already - an exception is thrown & (unfortunately) caught by the above mechanism, which led to a rollback (= delete of an existing project).

The fix for this also extends an automated test to verify rollback / cleanup is NOT called

**Comment by segator** [comment]
Can we have the fix released on 2.x? I don't think we have a breakng change on the api.

**Comment by clemensutschig** [comment]
@segator See #347 this is the 2.0 based pr
