### ISSUE TITLE
NPE in provision api method updateProject can potentially trigger project cleanup

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#351]
**Describe the bug**
Method call to ```ProjectAPIController.updateProject``` does not handle NPE. A triggered NPE in this method is cought by the block that catch exceptions of type ```Exception```. This catch block cleanups project if enabled by configuration. This could potentially cause a project removal. 

**Expected behavior**
Unexpected/Runtime exceptions should not cause removal of project.

**Affected version (please complete the following information):**
 - OpenDevStack [2.x]

**Comment by stitakis** [comment]
an update on this... so far, I was not able to reproduce... I'll investigate a bit more

**Comment by michaelsauter** [comment]
As it hasn't been updated, I'm moving to v4.

**Comment by clemensutschig** [comment]
I very much doubt that a call to `updateProject` can cause project removal (it calls `cleanup(LIFECYCLE_STAGE.QUICKSTARTER_PROVISION, updatedProject)`) internally which only goes after repositories.
