### ISSUE TITLE
AD Group set on all the created projects as admin by prov-app

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#364]
**Is your feature request related to a problem? Please describe.**
When support teams wants to help users to fix theirs issues on OCP can not even have access to the project.

**Describe the solution you'd like**
ODS Support team should have admin access on all the projects created by prov-app on Openshift.
To do this is as simple as update prov-app project creation script to add admin role to a specific AD Group set per parameters in the rest API or in the config of prov-app

**Comment by clemensutschig** [comment]
I would STRONGLY discourage this - for security reasons. a cluster admin / jira admin can always do this by hand. Please do NOT implement this.

**Comment by stitakis** [comment]
@segator can be this closed?

**Comment by stitakis** [comment]
@segator can be this closed?

**Comment by segator** [comment]
@clemensutschig agree with you but we never will have cluster admin, so we can not fix users problems if we don't have the project admin before.
So I really think we need this.

**Comment by clemensutschig** [comment]
Disagree... we just Need a process to get those rights for you. And we have One.

**Comment by segator** [comment]
Then much better :) but last time I asked, answer was never will happens.
