### ISSUE TITLE
Logout from identity manager should be optional

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#365]
**Is your feature request related to a problem? Please describe.**
Currently the OAuth2 configuration requires to configure the logout identity manager endpoint.
This is not optional.
Problem is that in some environment users/admins do not want to logout from identity manager but just from the prov-app.

**Describe the solution you'd like**
Have a configuration property that allow to disable the logout redirect to identity manager for deployments where users do not want to logout from identity manager but just from prov-app.
Property could be named: ```idmanager.disable-logout-redirect``` and should default to ```false```

**Comment by stitakis** [comment]
@oalyman this would solve the logout problem when integration prov-app OAuth2 with AzureAD

**Comment by stitakis** [comment]
@stefanlack your thoughts on this?

**Comment by stefanlack** [comment]
@stitakis  sorry for answering late.

I think it is ok, but unfortunately I currently have no time for approving the pull request, I  am sorry to say that.

**Comment by stitakis** [comment]
@oalyman or @clemensutschig can you please verify? The change is backwards compatible and 100% unit tested.
@stefanlack who from Opitz could take a look?

**Comment by tjaeschke** [comment]
> @oalyman or @clemensutschig can you please verify? The change is backwards compatible and 100% unit tested.
> @stefanlack who from Opitz could take a look?

Checked it and it looks good to me.
