### ISSUE TITLE
Add e2e-spock-geb Quickstarter to ProvApp CM

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-provisioning-app#366]
We would like to serve the following quickstarter throught he provisioning app: https://github.com/opendevstack/ods-quickstarters/pull/91.

**Comment by stitakis** [comment]
@metmajer @clemensutschig @michaelsauter @oalyman is this feature needed in platforms 1.0 release?

**Comment by metmajer** [comment]
@stitakis Yes!

**Comment by stitakis** [comment]
@metmajer I'll add these lines in the corresponding config files (```.../ocp-config/prov-app/cm.yml```)
```
jenkinspipeline.quickstarter.e2e-spock-geb.desc=Other - Spock E2E Test
jenkinspipeline.quickstarter.e2e-spock-geb.repo=ods-quickstarters
```
```Spock E2E Test``` would be the displayed name. Looks good?

**Comment by metmajer** [comment]
@stitakis looks good to me, thanks!
