### ISSUE TITLE
Difficult to maintain adapter unit tests due a mix of spring test and mockito

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#378]
**Describe the bug**
Adapter unit test are difficult to maintain and easy to break due a usage mix of spring test annotation and mockito. E.g. instead of using spring profile and spring @MockBean annotation the tests uses spring annotations at class level and Mockito @Mock and @InjectMocks. This mix makes the test unstable and easy to breal

**Proposed solution**
Refactor the test to use only spring test annotations and support.

**Comment by michaelsauter** [comment]
As this is refactoring, it isn't a direct requirement for v3, so I'll move this off for now. Feel free to bring it back if you start to work on it. Just trying to get an overview of what still needs to be done :)

**Comment by stitakis** [comment]
I'll close this item as we are achiving this in  #638
