### ISSUE TITLE
Upgrade provision app to spring boot 2 and spring sec 5

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#39]
1.5.9 is horribly outdated

**Comment by clemensutschig** [comment]
For release 1 i suggest we uptake 1.5.12 which is the latest 1 version.. to Not bring too many possible bads.. @michaelsauter

**Comment by clemensutschig** [comment]
ok - upgrade to .15 works with a few tweaks, upgrade to 2.0.5 shows a gazillion of failed tests - something pretty serious on mockito spy must have changed :(

**Comment by michaelsauter** [comment]
Using 1.5.15 for v1 of OpenDevStack sounds good to me.

**Comment by stitakis** [comment]
Hi, someone working on this one? If is not the case, I´m happy to pick up this

**Comment by stitakis** [comment]
upgrade to sb 2.0.x done, we can now start working on the upgrade to 2.1.x and java 11
