### ISSUE TITLE
Provide a configuration to blacklist webhook creation by component type

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-provisioning-app#392]
**Is your feature request related to a problem? Please describe.**
Sometimes a webhook for your quickstarter is not desired. E.g. the release-manager quickstarter should not create builds while you configure / adapt the configuration of components that are part of your release.

**Describe the solution you'd like**
Be able to configure a blacklist of component types that avoids webhook creation for those.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by stitakis** [comment]
@oalyman is this feature about of skipping the creation/setup of the webhook in the bitbucket project when the app provision a new component?

**Comment by michaelsauter** [comment]
@stitakis correct

**Comment by stitakis** [comment]
Currently quickstarters are enabled with this configuration
```
jenkinspipeline.quickstarter.release-manager.desc=Other - Releasemanager
jenkinspipeline.quickstarter.release-manager.repo=ods-quickstarters
```
If we add a property there like: 
```
