### ISSUE TITLE
Project Dashboard that provides project inventory details

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#393]
**Is your feature request related to a problem? Please describe.**
Currently operation of a project in ODS requires to go into each server management tool to collect information about the project inventory. An overview that collects all information is missing.

**Describe the solution you'd like**
A Project Dashboard in ProvApp should provide information about the project inventory like:
bitbucket project, jira project, confluence project, openshift: list of namespaces (cd, dev, test, etc...), components versions, routes, etc...

**Comment by stitakis** [comment]
@segator can you please quickly verify if this capture your request?

**Comment by segator** [comment]
Well maybe prov-app should provide the metrics but the UI for that should be an existing dashboard tool like grafana or kibana maybe, no?

**Comment by stitakis** [comment]
yeah... product like grafana are good to display time-based metrics.
The idea of the Project Dashboard is to provide a quick overview about which components are running in openshift in which namespaces, etc... Additionally, the corresponding version of it. Which routes are exposed to internet. 
All details that give a good overview to operations of what is deployed and running.
Links can be provided to make it ease to jump to the specialized tools.

**Comment by michaelsauter** [comment]
I would take a pause here and reflect where we want to go with the provisioning app. 

Many developers have already expressed that the provisioning app is difficult to work on, and that many things should be cleaned / refactored. In this current state, I would not recommend adding a whole new aspect to it. Also, I am wondering if the prov app is the right place for such a feature at all - it seems like an unrelated concern to "provisioning".
