### ISSUE TITLE
Provisioning App should set the Project Permissions only on group basis. No user references

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-provisioning-app#40]
When creating a new project, the project permissions for administrator/owner is set on a user Basis. they should be group based and optional user based. This is especially True for confluence and for bitbucket

**Comment by clemensutschig** [comment]
except for the CD_USER which is seeded now by default - no other users are seeded in case of create special permission set

**Comment by SimonGolms** [comment]
@clemensutschig - agree

**Comment by clemensutschig** [comment]
fixed as much as possible - can't prevent the setting of the user that created the space .. :(
