### ISSUE TITLE
Parameterise jira project type templates

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#404]
**Is your feature request related to a problem? Please describe.**
Currently jira project templates are hardcoded in the application properties. This is a problem if company related templates need to be added.

**Describe the solution you'd like**
Externalise jira project template to tailor configuration.

**Comment by stitakis** [comment]
@martsec 
adding project type template as parameter in the configuration will not fully make project type configurable.
Other additional properties are required to configure a project type.
For this reason this will require a bit more thought about how to make project type fully configurable with parameters.
I'll propose to move this to September2020 milestone.

**Comment by martsec** [comment]
I don't see how tailor fits into Atlassian project provisioning. Do you mean the configuration used to deploy the prov-app?

**Comment by stitakis** [comment]
Yes, I mean the configmap definition used by the deployment configuration of ProvApp -> the prov-app configuration is defined in ods-core project and it is located in the file `ods-provisioning-app/ods-config/cm.yml`. Jira project templates properties are defined there.
