### ISSUE TITLE
Jenkins create project job uses env.BITBUCKET_HOST and not configured application.properties' one

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#407]
**Describe the bug**
If one wants to use provision app against another (or more than one) bitbucket ... it should be good enough to tweak the provision app's CM to point to the new bitbucket / jira ... host.

This will ensure that the resources are created on the right bitbucket (e.g. project / repo) - BUT the jenkins job / webhook proxy that is called, does not get the bitbucket URL as param, but rather takes the one configured within jenkins.. (which is the "default" cluster configured one)

https://github.com/opendevstack/ods-core/blob/master/create-projects/Jenkinsfile#L16

based on
 
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java#L374-L389

@michaelsauter  / @stitakis  - did I see this correct?

@metmajer fyi

**Comment by michaelsauter** [comment]
@clemensutschig yes I think you are correct. That should be read from the build params probably?

**Comment by stitakis** [comment]
@clemensutschig @michaelsauter @metmajer I have debugged the code to verify what the ProvApp is including in the webhook http request params/body:
- create project: it does NOT include in http request the bitbucket server url (defined in application properties bitbucker.uri.
- create quickstarter: it does include in http request the bitbucker server url.

It will be an easy change to add the bitbucket server url to the create project http request. Webhook proxy changes will be needed.

**Comment by clemensutschig** [comment]
@stitakis  - yes .. lets go ... can you make this a priority?
