### ISSUE TITLE
Improve configuration of readable repositories

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#412]
If a project specific CD user is used, then it is given access to a list of repositories under the `opendevstack` Bitbucket project. That list is configured in https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-app/cm.yml#L131-L133.

There are a couple of issues with this:

1. By default, it does not contain the `ods-document-templates` needed for the MRO when documents should be generated.
2. The list is hardcoded, making it hard to use `tailor diff/apply` against it when someone changes the list in the web console. Unfortunately, it is hard to change it to be parameterised right now, because OpenShift Templates (which is what Tailor uses under the hood) do not allow to parameterise multiple lines easily.

I think the most pragmatic solution would be to change:
```
scm.global.readablerepos.opendevstack[0]=ods-jenkins-shared-library
scm.global.readablerepos.opendevstack[1]=ods-quickstarters
scm.global.readablerepos.opendevstack[2]=ods-mro-jenkins-shared-library
```
to:
```
scm.global.readablerepos.opendevstack=${READABLE_OPENDEVSTACK_REPOS}
```
where `READABLE_OPENDEVSTACK_REPOS=ods-jenkins-shared-library,ods-quickstarters,ods-mro-jenkins-shared-library`. Then the prov app would need to transform into a `List`.

Thoughts or alternative suggestions @oalyman @stitakis?

**Comment by stitakis** [comment]
@michaelsauter the proposal of moving the readable repos to list (`${READABLE_OPENDEVSTACK_REPOS}`) sounds good to me. Change looks easy to implement.
