### ISSUE TITLE
Uptake of new shared library for provision app - and harmonization of env mapping

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#415]
**Is your feature request related to a problem? Please describe.**
With the massive refactoring of the shared library - prov app (and all other buildable ODS components) should uptake it
1. provision app
2. document-generation-service
3. mro-shared-lib

also - I vouch for equal config - when it comes to environment mappings
```
  branchToEnvironmentMapping: [
    '*': 'dev',
    "${odsGitRef}" : 'test'
  ] 
```
@michaelsauter  - thoughts?

**Comment by michaelsauter** [comment]
This has been done in latest master of prov-app/doc-gen.
