### ISSUE TITLE
Errors during project creation are not exposed

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#427]
During project creation, things can go wrong. For example, it might not be possible to create a PVC because there is not enough disk quota left. This can be seen in the Rundeck logs, but it is not immediately visible as the job is marked as successful. To notice the problem, one needs to figure out that the failing Jenkins pod is due to a missing PVC, and then to look into Rundeck to see the actual error.

Could we somehow make this more obvious?

**Comment by stitakis** [comment]
@michaelsauter does jenkins provides an easily consumable api that we could use to query the status of a pipeline?

**Comment by michaelsauter** [comment]
Not sure - one could use the OpenShift API as well.

Note that you were probably notified of this because I transferred the issue from an old repo - no immediate action required.

**Comment by stitakis** [comment]
I think this is not actual anymore. The preconditions checks provides a fine grained error message. I'll close this item.
