### ISSUE TITLE
Select pr:deleted event when creating webhooks

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#429]
Follow-up from https://github.com/opendevstack/ods-core/pull/527.

**Comment by stitakis** [comment]
@michaelsauter what need to be done here? can you please briefly explain?

**Comment by michaelsauter** [comment]
Add like this: https://github.com/opendevstack/ods-provisioning-app/blob/324124c41fb42840f6f891bc60b2a41dc8e44e0c/src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java#L511

**Comment by stitakis** [comment]
ok, what about of making this configurable by creating a config property with comma-sep values. e.g `webhook-proxy.events=repo:refs_changed,pr:merged,pr:declined,pr:deleted` ?

**Comment by stitakis** [comment]
@michaelsauter I'm fixing this... PR will be ready in few minutes
