### ISSUE TITLE
Make central namespace configurable

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#430]
Follow-up from https://github.com/opendevstack/ods-core/pull/528.

We need to make two things configurable:

- Where is the webhook proxy located? Currently this is hardcoded to `prov-cd` - but going forward this should be configurable, with the default being `ods`.
- Where are central images (Jenkins slave etc.) located? Currently this is hardcoded to `cd` but going forward this should be configurable, with the default being `ods`. See https://github.com/opendevstack/ods-jenkins-shared-library/issues/311.

@oalyman Would you mind having a look into this?

**Comment by michaelsauter** [comment]
@oalyman Isn't this done already?

**Comment by oalyman** [comment]
@michaelsauter 

> Where is the webhook proxy located?
https://github.com/opendevstack/ods-provisioning-app/blob/master/openshift/cm.yml#L233-L235

> Where are central images
This is part of ods-core and was changed as well.
