### ISSUE TITLE
available quickstarters endpoint

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#431]
**Is your feature request related to a problem? Please describe.**
As REST API consumer I'd like to be able to get a list of available quickstarters

**Describe the solution you'd like**
Provide an endpoint that provides a list of available quickstarters

**Comment by stitakis** [comment]
@martsec @metmajer fyi

**Comment by stitakis** [comment]
@martsec @metmajer when I created this github issue I thought we need to implement an endpoint that provide a list of available quickstarters. Actually I was wrong. The class `QuickstarterApiController.java` exposes the endpoint `api/v1/quickstarter`. So far all 3 endpoints including this one requested by Alan are implemented already.

**Comment by stitakis** [comment]
@alanbort fyi

**Comment by metmajer** [comment]
@stitakis @alanbort @martsec consider that every Quickstarter contains a metadata.yml file with descriptive data. Can you serve this data through the endpoint?
