### ISSUE TITLE
Split / Separate "tracking projects/documentation" from source control

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#44]
Hi All This in regards to the Atlassian suite w.r.t to BITBUCKET as this is a code repository would recommend to
segregate the usage from JIRA and Confluence. As the user/project requirement in some cases be different for all three applications.
And i would like to recommend to provision all three application separately

Cheers

**Comment by clemensutschig** [comment]
@borja44  - I can understand the split -> jira&confluence ||| Bitbucket... that may be supported in the future. 

Current logic: create bitbucket repo / project in ANY case - no matter if you choose atlassian &| openshift

No support for all 3 - jira w/o confluence does not make any sense

**Comment by clemensutschig** [comment]
@borja44 - fix is to create the bitbucket project only when openshiftproject == true.
