### ISSUE TITLE
Provision app - github action build should create / add labels during build

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#441]
https://github.com/opendevstack/ods-provisioning-app/blob/7796d2beba7510f5ed6c42593df056d24e853014/.github/workflows/gradle.yml#L28

in order to have tracibility - the following labels should be added - taken from (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/BuildOpenShiftImageStage.groovy#L94-L101)

1. ods.build.source.repo.url
1. ods.build.source.repo.commit.sha
1. ods.build.source.repo.commit.msg
1. ods.build.source.repo.commit.author
1. ods.build.source.repo.commit.timestamp
1. ods.build.source.repo.branch
1. ods.build.jenkins.job.url -> the github job url
1. ods.build.timestamp

most of the things are available by default:
https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

**Comment by oalyman** [comment]
@clemensutschig I propose to change the key `ods.build.jenkins.job.url` to `ods.build.job.url`

**Comment by clemensutschig** [comment]
Works :-)

Jan Frank <notifications@github.com> schrieb am Do., 14. Mai 2020, 16:35:
