### ISSUE TITLE
reuse application properties from src/main/resources in openshift to simplify configuration

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#446]
**Is your feature request related to a problem? Please describe.**
Simplify configuration by reusing application properties.
Currently application properties contained in src/main/resources are fully duplicated in cm.yml.
This is because the docker file override the `spring.config.location` property to just one location `--spring.config.location=classpath:/,file:/config/`.
This is wrong. Composite configuration based on default provided by application.properties and overrides provided in file:/config/ should be allowed to facilitate property overrides over time.  
Currently only 1/3 of the configuration is overriden and parameterized.

**Describe the solution you'd like**
Change in Dockerfile, the spring config location from:
`CMD ["java", "-jar", "app.jar", "--spring.config.location=file:/config/"]`
to
`CMD ["java", "-jar", "app.jar", "--spring.config.location=classpath:/,file:/config/"]`
Adding `classpath:/` before `file:/config/` will instruct spring to load the properties first from the first location `classpath:/` and the overrided from the 2nd location `file:/config/`.

The `cm.yml` will need to be modified to include only the application configuration overrides.

**Comment by stitakis** [comment]
@michaelsauter @oalyman @clemensutschig soungs good? It is a big improvement and resolves a big pain point for me :-)

**Comment by michaelsauter** [comment]
Sounds good to me.

**Comment by michaelsauter** [comment]
@stitakis What exactly is your pain point with this? I talked this over with @oalyman today and agree with his view that it could be dangerous to have "hidden" config in the image ...

**Comment by stitakis** [comment]
@michaelsauter we have 2 sources of configuration `cm.yml` and `application.properties` and we are not using wisely the spring configuration features that allow developer to enable profiles.  

Regarding "hidden" config:
- I think defaults should not be duplicated and configured explicity. Secrets and environment configuration instead need to go in `cm.yml` defined as parameters. We are not reinventing the wheel here.
- Also I assume that ProvApp deployer will check the documentation in advance.
- But if Admins would like to verify runtime configuration we could easily show the efective configuration throu the Actuator endpoint.

Anyway, I'll provide a draft PR once I have time to polish a prototype of this feature that I built.
