### ISSUE TITLE
setup webhook in jira projects on project creation event

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#452]
**Is your feature request related to a problem? Please describe.**
To integrate Jira to be able to trigger Jenkins jobs we need to configure a webhook in the jira project at creation time.

**Comment by stitakis** [comment]
@georgfedermann @michaelsauter

**Comment by clemensutschig** [comment]
This is close to impossible in the current architecture - because we cannot pass params from the prov app down to the jenkins job or the plugin .. there was an issue somewhere to allow this - but this is a pretty massive change. That I would IMHO tackle for 4 and not for ODS 3

**Comment by michaelsauter** [comment]
@clemensutschig Couldn't this be done from the prov app itself? I think it is just about setting the URL in Jira somewhere, and the URL we know ...

**Comment by stitakis** [comment]
@michaelsauter @clemensutschig this is a feature request comming from BI. The EDP plugin will/have a REST API endpoint that allows to set properties. I haven't heard nothing about this in that last week. I'll move this item to OpenDevStack 4... agree?

**Comment by metmajer** [comment]
@stitakis you should rather double check with @martsec if you haven’t already...

**Comment by stitakis** [comment]
@martsec I forgot to include you on this thread. My apologies. I guess, we should schedule this item for ODS 3.1/September, right?

**Comment by stitakis** [comment]
this feature is branch `3.x`. I'll port it to master as next step
