### ISSUE TITLE
Unnecessary privilege for jenkins cd user

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-provisioning-app#472]
**Is your feature request related to a problem? Please describe.**
`jenkins Cd User` is given more privileges inside a repo than it actually needs. This happens every time a component is generated for all pre-existing components. 
The user is given admin privileges as specified [here](https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java#L601). It just needs `write` permission. With admin it can act as a repo owner.

**Describe the solution you'd like**
Switch from admin privilege to write.

**Comment by sino92** [comment]
@gerardcl @stitakis

**Comment by clemensutschig** [comment]
on project level the `cd user` needs admin rights - to create new repositories ... (during quickstarter provisioniong.

I think when set on project level., you cannot overwrite (lower permissions) on repo level

**Comment by sino92** [comment]
Hmm if I got it right, `BitbucketAdapter` inherits from `BaseServiceAdapter` which eventually makes the request to Atlassian services. The init of `BitbucketAdapter` completes the atlassian specific technical user to make the request. That technical user is concatenated to user `.admin_user` `.admin_password`. So when you init BBAdapter then the user to create project/repos become bitbucket.admin_user which points to `provision_app_test`. This user is part `eu_dx_user` group and already has project creator privileges.
`provision_app_test` creates the repos and `cd user` pushes its contents during quickstarter pipeline

**Comment by clemensutschig** [comment]
@sino92  - sorry I am not following.
maybe post a screenshot of the rights / roles on a bitbucket repo - so we can see this?!

**Comment by sino92** [comment]
At the global level, `eu-dx-user` has project/repo creator permissions.
![Screen Shot 2020-06-19 at 11 47 11](https://user-images.githubusercontent.com/16910110/85119941-d1fef280-b222-11ea-8fb6-f4804b58fd76.png)
`provision_app_test` is part of that group. So it can create any project/repos by default.

**Comment by stitakis** [comment]
@clemensutschig I think, the `cd_user` just only need read permission to be able to clone the opendevstack repository `ods-core`, `ods-jenkins-shared-lib`, etc... Thou I haven't verified this extensively. 
@sino92, The ProvApp metioned above uses SSO and a service account. Please remove from your messages above all references to current setup. Due security, we shouldn't post this kind of details.

**Comment by sino92** [comment]
`cd_user` also needs write permissions to repo otherwise it can't push documents generated by quickstarters to repo.

**Comment by sino92** [comment]
@stitakis Not sure if I got your comment about SSO and service account. Any comments about the technical non-cd user that creates the project/repos?

**Comment by stitakis** [comment]
@sino92 the behaviour of ProvApp is different if you use configuration `crowd` or `oauth2/sso`. For `oauth/sso` a service account is needed.

**Comment by sino92** [comment]
@stitakis Is there any documentation on the after-effects of crowd/sso setup? Either way it shouldn't affect this issue as long as `BaseServiceAdapter` is still used. Or its not? As far as I can tell the authenticator user doesn't influence the technical user that makes the Atlassian service specific request.

**Comment by stitakis** [comment]
@sino92 afaik the code is the documentation in this case... I'm in favor of this change. It is always a good idea to remove unnecessary permissions. Changes that implement this issue will need to deal with both authentication mechanism.

**Comment by sino92** [comment]
@clemensutschig I'd be happy to clarify any confusions in a call, if any
