### ISSUE TITLE
unknown exception (e.g. existing JIRA project) raised in REST create project endpoint / addProject causes removal of existing projects

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#514]
Incomplete provisioned projects are cleaned up in case of exception in the create project endpoint.
However, when a project do not exists in local storage, current implementation triggers an exception when it tries to create a project e.g. in Bitbucket.
This causes the execution of the cleanup and removal an existing project in atlassian servers and openshift.

Proposed solution:
- only allow to cleanup project if project does not exists in local storager and in atlassian servers.

**Comment by michaelsauter** [comment]
Maybe related to #351.

Moving to v4 as it hasn't been updated.

**Comment by clemensutschig** [comment]
This is dort of intended.. if someone removes History..  how are we supposed to know? Ill dig tmrw into this and try to understand it

**Comment by clemensutschig** [comment]
Quick update - we could .. ? ... check if the project in jira exists, and if so - let go .. this is pretty surgical _ but again, as all projects should be created thru the prov app - I think this is a pretty extreme cornercase - especially given that we very if the key exists if you go via the UI - so this can only happen in the case of using the REST API ..

@michaelsauter  - thougts?

**Comment by michaelsauter** [comment]
@clemensutschig I like that idea.

Long-term, I'm not sure if the history of the prov app should be so important. I think we now have two pretty common use cases which suffer from this "history as source of truth" approach:

* Migrating projects to another cluster - the prov app in the target cluster does not know about the migrated project, so people cannot provision quickstarters
* Multiple ODS installations within one cluster - there is no way to use the prov app from another installation to provision quickstarters
