### ISSUE TITLE
Provide modern SPA user interface to improve UX

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#518]

**Comment by netzartist** [comment]
The current UI lacks a good usability which leads to misuse especially for non-technical users and requires extra caretaking when entering/editing data.

**Main goals:**

- Improve the overall user experience incorporating latest usability best practices
- Provide a modern tech stack to allow long-term maintainability and keep high code-quality 

**The new UI layout** consists of a:

- Sidebar to quickly navigating to an existing project or create a new project
- Detail view showing all information compact and clear including component's data (via expand/collapse toggle) and a switch between edit-/view-mode

**Features:**

- The same like in the current UI, plus
- 'Delete project' functionality
- 'Delete component' functionality

![image](https://user-images.githubusercontent.com/370980/87682141-c9490000-c77f-11ea-8c79-848e13611fcd.png)

As there are some open tasks to be finished, the new UI will be included as an experimental feature in ODS 3.x release, deactivated by default. It can be activated by an admin with a `frontend.spa.enabled` feature flag in Spring Boot.
