### ISSUE TITLE
Not possible to add new component in an non OpenShift project

### ISSUE THREAD

**Issue by netzartist** [opendevstack/ods-provisioning-app#549]
**Describe the bug**
Given a new project is provisioned without OpenShift option, adding a new component always results in an error:

`FOOPROJECT cannot be upgraded to openshift usage`

**To Reproduce**
1. Create a project with "Create OpenShift projects" option not checked
2. After creation, choose 'Modify Project'
3. Add a new component with a vaild name
4. See error in modal

**Expected behavior**
- Adding new components in non OpenShift projects should be possible or
- Inputs to add new components shouldn't be shown

@michaelsauter @clemensutschig Thoughts? Why not always create OpenShift projects (= showing no checkbox to the user at all)?

**Comment by clemensutschig** [comment]
That is very intended... We schuld Not even show the possibilty if its a
non openshift Project.. the Flag is called PlatformRuntime i think

Jan Deppisch <notifications@github.com> schrieb am Mo., 27. Juli 2020,
10:22:

**Comment by michaelsauter** [comment]
@netzartist Some only want the Atlassian suite, no OpenShift. For example, you might develop against AWS or so.

**Comment by netzartist** [comment]
@clemensutschig @michaelsauter Ok, thx, then I'll disable the inputs in this case.
