### ISSUE TITLE
wrong name format in ods component creation at ods jira projects

### ISSUE THREAD

**Issue by jssnull** [opendevstack/ods-provisioning-app#565]
**Describe the bug**
In an ods project we’ve been testing to create a quickstarter using provisioning app,
For example, if we use the MYPROJECT project and we deploy a quickstarter called python-flask-myproject (using the project key of our ods project in our new app name), 
As we can see in the image this application will be created with the name given in bitbucket.
<img width="439" alt="bitbucket-myproject" src="https://user-images.githubusercontent.com/12979859/89393638-5e01a680-d70b-11ea-989a-909f8685d8c3.PNG">

But would be shown in the following format in the components section in our ods project in Jira:
![jira-myproject-2](https://user-images.githubusercontent.com/12979859/89394638-9b1a6880-d70c-11ea-9ab2-260791ee21e0.png)

In a nutshell, the app name in Jira components section wouldn’t contain the entire project key name. 
It seems that this produces incoherences between Jenkins Jobs and Jira components,  then, the ods autodocgen generation will fail
 
**To Reproduce**
1. Go to prov-app
2. Click on Provision tab
3. Click on modify existing project and select your project
4. Select the quickstarter you will use
5. use a component-id that contains your ods project name
6. Click on start provision
7. In Jira the component will appear without the project key  name
<img width="139" alt="jira-component-name" src="https://user-images.githubusercontent.com/12979859/89395785-0fa1d700-d70e-11ea-9a2d-847942cd3b45.PNG">

**Expected behavior**
It should create the component in Jira with the project key name in component name

**Screenshots**
Already attached

**Affected version (please complete the following information):**
 - OpenShift: [3.9, 3.11]
 - OpenDevStack [2.x]

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JiraAdapter.java#L517

Is the curlprit... want to submit a pr.. ? You could just replace the first hit.. which is the prefix project

**Comment by jssnull** [comment]
Hi,
at the moment I don't have an OpenDevStack development environment with a prov-app instance for testing that change before sending a PR

The PR could be made by anyone else? 

Best Regards
