### ISSUE TITLE
Raise Permissions on Confluence Groups when special permission set = true

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#57]
We've detected the permissions assignation on the 3 different GROUPS for CONFLUENCE SPACES that have some permission-attributes DISABLED.

MANAGER - 
STAKEHOLDER - 
TEAM - 
![permissiosn](https://user-images.githubusercontent.com/10860118/48624429-a794e580-e9ac-11e8-83ad-9859f36ec9e9.png)

**Comment by clemensutschig** [comment]
permissions in question

- REMOVEATTACHMENT
- REMOVEPAGE
- REMOVECOMMENT

**Comment by borja44** [comment]
Hi @clemensutschig this is not a blocker, but we are already using this script and we've to modify one by one manually all current created groups spaces, so, this means is important.

I'm also clarifying permissions:

**MANAGER**
- REMOVEPAGE
- REMOVEATTACHMENT
- REMOVECOMMENT

**If** a user accidentally adds an attachment/space/comment will have to wait for the space admin rather than the team manager.

**Comment by clemensutschig** [comment]
@borja44  - please verify on premise - with the link I provided - target for prod -> friday 6pm

**Comment by clemensutschig** [comment]
**
![image](https://user-images.githubusercontent.com/40628552/48780125-72a0cf80-ecd9-11e8-9250-ed9e209f5430.png)
**
