### ISSUE TITLE
git url created from Bitbucket 5.13.0+ does not follow conventions

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#58]
Normally, we expect in the downstream jobs (e.g. when creating the pipline build configuration), that the http git url contains the technical user.
The logic sits in BitbucketAdapter. It expects that the clone url returned by bitbucket contains the username of the currently logged in user.
This behavior seems to have changed from Bitbucket 5.13.0+ on. The clone url does no longer contain a username.
Thus the URL is not correctly created for downstream jobs.

**Comment by clemensutschig** [comment]
Richard whats the issue here? This works well in premise

**Comment by clemensutschig** [comment]
@rattermeyer  - we run Atlassian Bitbucket v5.13.0 

and I just checked prov app from last weeks ... - no user in there ... 

    },
    "booth1-fe-angular" : {
      "clone" : [ {
        "name" : "ssh",
        "href" : "ssh://git@bitbucket-dev.....:7999/booth1/booth1-fe-angular.git"
      }, {
        "name" : "http",
        "href" : "https://bitbucket-dev...../scm/booth1/booth1-fe-angular.git"
      } ],
      "self" : [ {
        "name" : null,
        "href" : "https://bitbucket-dev...../projects/BOOTH1/repos/booth1-fe-angular/browse"
      } ]
    }
  },

and it all worked ...
@torstenhe  - anything you saw that did NOT work?

**Comment by rattermeyer** [comment]
The bug is shadowed by a ["hack"](https://github.com/opendevstack/ods-jenkins-shared-library/blob/12845dbee2f2ab9308561f7f0905e918cb3c46c9/src/org/ods/OdsContext.groovy#L298) in the jenkins shared library. If your bitbucket host by chance is called "bitbucket" the shared libray again inserts the cd_user. This should be configurable and not hard coded.
@tjaeschke wanted to file an issue for that as well.

**Comment by clemensutschig** [comment]
@rattermeyer- approved.. Please ensure no regressions.. aß we come to v1.. we have to be super carefull
