### ISSUE TITLE
Missing unix basic commands on prov-app after deploying ODS 3

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#588]
**The linux commands (vi, less, more) are not on the base image of prov app on ODS 3.**

1. Go to openshift -- terminal
2. Click on ods project and select prov-app pod
3. Click on terminal
4. Execute commands on terminal, **(vi less more or nano/pico not installed...)**

This basic commands should be included in order to be able to do at least a minimum troubleshooting with the docker container... Operations/Maintenance...

Will be interesting to have an alternative way to operate, using API calls or using other docker base image

**Affected version :**
 - OpenDevStack 3.0

![image](https://user-images.githubusercontent.com/10860118/91848718-2aa72e80-ec5b-11ea-9526-297e81e70f04.png)

**Comment by stitakis** [comment]
@borja44 I can imagine your surprise when you find out that tools like `vi`, `less`, etc... are not installed.... 

Background: for ODS 3.0.0 the docker base image was changed for provisioning app to `adoptopenjdk/openjdk11:ubi-minimal-jre`. This is based on `minimal` ubi image flavour from RedHat (more here: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image). The selection of the `minimal` image was done on purpose to increase security.

However, for enterprise deployments I can understand that this can be seen as too restrictive. 

To provide the tools that you are requesting we need to change the base image to `adoptopenjdk/openjdk11:ubi-jre`.

@michaelsauter what do you think? Should we change to `adoptopenjdk/openjdk11:ubi-jre`?

**Comment by michaelsauter** [comment]
I would be OK with switching to `ubi-jre`. @oalyman objections?

However, I would like to understand what you were trying to do first. Why did you need those tools? What problems were you facing so you needed them? Even if we install the tools, it would be good to figure out if the actual problem isn't located elsewhere ...

**Comment by borja44** [comment]
would be fine if project provides another FE based on API calls to prov-app instead of using directly the yaml database. 
But there are problems like: -problem with wrong creation, -manual creation of project, -deletion of quickstarter, -deletion of a project ... -logs troubleshooting, -webhook proxy modification (not so common), -cduser account modificate configuration ....

**Comment by michaelsauter** [comment]
@borja44 so most of the issues are admin tasks related to the project / component storage? maybe this is something we should have a frontend for that admins can access. @segator @stitakis what do you think?

**Comment by stitakis** [comment]
My point of view regarding the topic "missing tools in the pod": 

- case "file edition": I can't think of a use case of editing a file in the pod. Changes in configuration are normally done with the openshift console. The tool `cat` is available and from my point of view good enough to show content of small files. 
- case "config changes": these are normally done in the openshift console with config map editor. A restart of the pod is required afterwards.
- case "read of log files": the tool I missing here is `less` (`more` is also not available). Without one of these tools read of log files is very difficult. (While admins can copy files with `oc cp` command to local machine is not an ideal case)

Regarding missing functionality in the FE and ODS/cluster admin operation:
- the history view is not very useful. It only displays basic details of each project. But it doesn't show audit information of the project, like who created it, which components were added and when... etc. Such information could be useful for cluster administrator and ODS support to understand the evolution of a project.

My proposal... @borja44 let us discuss this together to have the whole picture and define a roadmap. Goal would be the to capture the missing feature to make the operation of prov-app easier and more effective. Sounds good?

**Comment by segator** [comment]
Make the docker image as clean as possible is correct, the problem here is the lack of tools to make admin job easy, in provapp comon tasks is check project and quickstater logs and edit by hand json project file because incosisntencies in the project creation

**Comment by stitakis** [comment]
@segator @borja44 for coming release in September I'll change to base docker image `adoptopenjdk/openjdk11:ubi-jre`. This will solve the problem of missing tools. Sounds good?

**Comment by michaelsauter** [comment]
I'm fine. Please open a follow-up ticket though that we have a closer look at what admin tasks need to be performed in one of the upcoming ODS releases.

**Comment by stitakis** [comment]
Done, I've opened a follow-up ticket -> #602

**Comment by stitakis** [comment]
@borja44 would be 'vi'  and 'more' enough for you or do you need another tool
