### ISSUE TITLE
check project name exists is only performed against jira and not openshift.

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#589]
The provision functionally offers the option to create only an openshift project.
However the project exist check only is performed against Jira.
This is an inconsistency that we need to fix to avoid random E2E test failure.

Proposed solution:
Add logic that verifies per API call against openshift if the project key exists in openshift.

**Comment by stitakis** [comment]
@martsec this is required to improve stability of E2E test.

**Comment by stitakis** [comment]
@metmajer I'm descoping this issue from ODS 3.1. I'll not be able to implement it before release date in october.

**Comment by michaelsauter** [comment]
@clemensutschig This is the "OpenShift connection" from the prov app I mentioned last week. Do you want to have a look into this?
