### ISSUE TITLE
Spike: Permissions schemes in Jira - project roles / ... 

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#63]
Permissions schemes in Jira should type permissions to project roles and not directly to permission groups

**Comment by clemensutschig** [comment]
@borja44  - sorry but I dont understand this reqiurement .. how does that tie to groups coming thru crowd?

**Comment by borja44** [comment]
I've transferred this information to an expert on this topic so, he'll back via mail to me and will update it here

**Comment by borja44** [comment]
closed by error, reopen again

**Comment by borja44** [comment]
go to [https://github.com/opendevstack/ods-provisioning-app/issues/91](url)

**Comment by clemensutschig** [comment]
see #151
