### ISSUE TITLE
Openshift service adapter is timing out with openshift 4

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#720]
The openshift service adapter is timing out on API calls with red hat dedicated oc4.

The current used openshift library uses openshift 3.x API, which is probably is not enabled anymore in dedicated oc4.

While this needs to be confirmed, the solution to this problem would be an upgrade of the library to support oc4 API.
However, we should decide if we want to maintain support for oc3. If this is the case, we would need a way to provide to openshift adapters and import the corresponding libraries.

As first measure we should change the behavior to disable this service by default (#721)

**Comment by clemensutschig** [comment]
did you folks try with the OCP4 libs, and that works? - just asking :) should be easily reproducable locally, or?

**Comment by oalyman** [comment]
I think you need to use this as an alternative https://github.com/fabric8io/kubernetes-client/

**Comment by stitakis** [comment]
I haven't used the ocp4 libs yet... I'm currently focusing on other topics... if you time to fix, I'm happy to give a hand
