### ISSUE TITLE
provisioning app should support lower level container based projects

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-provisioning-app#77]
The provisionig app should also support lower level deployments based on simple and complex Dockerfile container definitions.

**Comment by michaelsauter** [comment]
@tbugfinder Could you elaborate? I'm not sure I understand what you are trying to achieve ... are you talking about another type of quickstarter? The provisioning app does not dictate what kind of projects / deployments you do ...

**Comment by tbugfinder** [comment]
Oh, correct - actually I meant another slim quickstarter which sets up the defined "environment" but has a focus on lower level - like provision containers based on e.g. on a Dockerfile(s). Not all projects are tight to nodes.js and those higher level frameworks.

=>close/move this issue?

**Comment by clemensutschig** [comment]
@tbugfinder- move to ods-project-quickstarters. Today we only offer high level quickstarters .. but those are based on dockerfile etc. So you could provision just about any quickstarter to make this work.. but its a great idea.. do you want to contribute it?

**Comment by tbugfinder** [comment]
created [quickstarter-issue](https://github.com/opendevstack/ods-project-quickstarters/issues/97)

Therefore closing this one.
