### ISSUE TITLE
Provision app created jira project does seed rights to read a project for -readonly groups

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#85]
I've just noticed than the default permissions on a jira project after the provisioning app, does not have the ability to read a project for -stakeholders group. 
![image](https://user-images.githubusercontent.com/10860118/51988082-1bbb3180-24a4-11e9-8d0f-6f5915393ed0.png)

**Comment by clemensutschig** [comment]
@borja44  - is someone not seeing a project he/she should, or what?
