### ISSUE TITLE
Create service framework to allow integration to other bugtrackers/scm & idmgt

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#86]
Today integration to jira/confluence and bitbucket is hardwired..  also the dependency to crowd for Identitymgmt - we should provide a Plug and Play Framework so other Tools can be plugged in..

**Comment by clemensutschig** [comment]
@tjaeschke- fyi...are you Working in this?

**Comment by rattermeyer** [comment]
We are not working on this. But we completely agree. Idmgt is a different kind of beast, than bugtrackers / scm. Think along the lines that you can define at deploy time which VCS, issue tracker and wiki you would like to use and having "modules" insinde the provisioning app handling requesting the required inputs and provisioning the target systems.

**Comment by clemensutschig** [comment]
I am on this now - it's really hard ... I will publish a WIP PR .. currently I am extracting interfaces ...
