### ISSUE TITLE
wrong (lean) project permissions in Bitbucket, when tight permission set configured

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#87]
There is a default permission after the provisioning app is executed on BITBUCKET. 

First is adding the user to a group called xxxxxxxdevstack-users, and, after that the same group is added into the $NEW-CREATED-PROJECT.

What is the problem?
Problem is that this group xxxxxxxdevstack-users has access to $ALL-PROJECTS and can write into them. 

Could be the possibility to remove this default Group Access for the provisioning app?
![image](https://user-images.githubusercontent.com/10860118/52423574-adf0b480-2af8-11e9-8cd2-371632eacffd.png)

**Comment by clemensutschig** [comment]
flagging this as bug .. too many rights - the gotcha is in 
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java#L267
