### ISSUE TITLE
No Default Notification Scheme assigned into Jira projects upon creation

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#90]
Hi
There is no Default Notification Scheme assigned after a Jira project is created and or the provisioning app is executed, and, has to be added each time manually.

Could be possible to add this feature for mail Notifications for any action on Jira?

**Comment by clemensutschig** [comment]
@borja44  - I assume you want the default notification scheme?

![image](https://user-images.githubusercontent.com/40628552/53422571-015f6f80-39e0-11e9-9987-54603da3f339.png)

**Comment by borja44** [comment]
Sure

**Comment by clemensutschig** [comment]
quick update on this - by default - the seed of the "Default Notification Scheme" - is with id 10000 (as every other object btw).

**Comment by borja44** [comment]
Yep yep 👍 

https://wathever.whoever.com/secure/admin/EditNotifications!default.jspa?atl_token=yopYopYopYopyupyupyupyepyepyep&**schemeId=10000**

**Comment by clemensutschig** [comment]
![image](https://user-images.githubusercontent.com/40628552/54346448-5be60600-4645-11e9-9193-d010f7e81d14.png)
