### ISSUE TITLE
Add default created -GROUPS to roles by default scheme on JIRA

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#91]
There could be the option to add the:
**a) $project-TEAM group on the **Developers role**** 
 
**b) $project-MANAGER group** on the **Administrators role ;

**c) $project-STAKEHOLDER group** on the **Stakeholders role ;

In to the software default scheme on Jira after the provisioning app is executed?

Role for -TEAM into Developers
Role for -MANAGER into Administrators
Role for -STAKEHOLDER into Stakeholders

![image](https://user-images.githubusercontent.com/10860118/53638295-16c5db00-3c26-11e9-9dbc-d7dcbf30f836.png)

Since Default permissions scheme are modified, anyone is inside the permissions scheme, and the $ProjectLeader has to add manually one by one for first time, could be much better if this is fully  automated.

Cheers,
Borja

**Comment by clemensutschig** [comment]
@borja44  - I am sorry, but I don't understand what you ask for ... at all - and what you attempt to solve with this proposal

**Comment by borja44** [comment]
What we want to avoid is making the Project Owner responsible to add manually all of this groups. 
Since the permissions are the default ones, the idea is basically to provide this basic project roles with the groups inside.

**Comment by segator** [comment]
Borja is asking if it's possible that prov-app assign multiple groups to diferents roles in jira when provisioning a new project via API in prov-app

**Comment by stitakis** [comment]
@borja44 this was implemented with #151
