### ISSUE TITLE
prov-app dev&test - rundeck api path / systempath - are hardcoded - should be params

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#93]
https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-app/cm.yml#L60-L61 

has hardcoded the api / system paths - this HAS to be configurable.

- system path is used for auth:
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/RundeckAdapter.java#L223
- api path is used for execution creation:
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/RundeckAdapter.java#L169

**Comment by michaelsauter** [comment]
As the 1.1 release date is tomorrow, I am moving this to 1.2.

**Comment by michaelsauter** [comment]
Rundeck has been removed.
