### ISSUE TITLE
Support technical user as an alternative authentication mechanism

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-provisioning-app#97]
Currently the user using the provisioning app needs general admin rights on some of the Atlassian tools.
To support a more self-service workflow it is required, that users can use the provisioning app, but without having all the admin rights in the downstream tools.
We therefore need a mechanism to alternatively specify "technical users" that are used for the interaction with the downstream tools.
It can be specified, if the credentials / tokens of the logged in users are used or the special technical user.

**Comment by clemensutschig** [comment]
@rattermeyer - we do this today already - with a tech user that is in a special group - that authenticates itself against /jsecurity and then calls the API.

I strongly oppose storing any key / credentials in the prov app

**Comment by clemensutschig** [comment]
<pre>
curl -D headers.txt -k -H "Content-Type: application/x-www-form-urlencoded" -X POST ${PROVISION_API_HOST}/j_security_check -d username=xxx-d password=yyyyy

login_status=$(cat headers.txt | grep ${PROVISION_API_HOST}/login?error)

if [[ $login_status != "" ]]; then echo "Login Error"; fi;

JSESSION_ID=$(cat headers.txt | grep "Set-Cookie: JSESSION" | cut -d ';' -f1 | cut -d ":" -f2)";" 
CROWD_COOKIE=$(cat headers.txt | grep "Set-Cookie: crowd" | cut -d ';' -f1 | cut -d ":" -f2)

COOKIES=${JSESSION_ID}${CROWD_COOKIE}

curl -k -X POST --cookie "$COOKIES" -d @"$provisionfile" -H "Content-Type: application/json; charset=utf-8" -v ${PROVISION_API_HOST}/api/v1/project
</pre>

**Comment by rattermeyer** [comment]
Not sure, if that matches requests. Use case is: allow "developers" to use provisioning app as self service portal, but because of jira permissions required it is not possible to give all these users "admin" access.
Not sure, if I understand your use case correctly though.

**Comment by stefanlack** [comment]
@clemensutschig : your solution is for crowd authentication only. 

@rattermeyer For oauth2 authentication, we have already implemented this requirement, as documented in https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/index.html#_authentication_to_third_party_apps_via_technical_users 

> The rest api calles use HTTP basic access authentication to communicate with Jira, Confluence, Bitbucket and Rundeck. The used credentials are read from a pair of properties. For Example, rundeck.admin_password and rundeck.admin_user properties are used for Rundeck, confluence.admin_user and confluence.admin_password are used for confluence, etc.

I think we can close this issue, do we?

**Comment by michaelsauter** [comment]
Let's close this.
